### ISSUE TITLE
URLs with paths ending in a directory do not load the contained index.html

### ISSUE THREAD

**Issue by jimmycuadra** [maidsafe/safe_browser#100]
Operation System: macOS 10.12.6
Beaker Version: 0.4.0 (Test 18)

I would expect safe://www.ruma/docs/ to be equivalent to safe://www.ruma/docs/index.html, but the former downloads a file to disk rather than rendering the directory's index.html in the browser.

**Comment by shankar2105** [comment]
Hi, @jimmycuadra which file gets downloaded to disk?

**Comment by shankar2105** [comment]
Thanks, @jimmycuadra. We have created a [task](https://maidsafe.atlassian.net/browse/MAID-2144) to resolve this issue.

**Comment by bochaco** [comment]
@jimmycuadra , this should be fixed on latest release. I'm closing it now but please let us know if you still have issues.
