### ISSUE TITLE
MacOS build & deploy on Travis timing out

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe_browser#1000]
Hit a timeout when we tried to deploy a release candidate here https://travis-ci.com/maidsafe/safe_browser/jobs/239395454#L1360

Is this a timeout value we can increase, or any indication what caused this?

**Comment by joshuef** [comment]
This should be solved by #1009

**Comment by S-Coyle** [comment]
Verified that the build issue with macOS is now resolved - https://travis-ci.com/maidsafe/safe_browser/builds/130178024
