### ISSUE TITLE
Issues with versioning reported by community

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#1007]
https://safenetforum.org/t/safe-network-dev-update-september-26-2019/29961/57?u=karamu

**Comment by S-Coyle** [comment]
very similar, related to #993

**Comment by joshuef** [comment]
I am not able to repro this on Mac no #993 w/ latest dev

**Comment by joshuef** [comment]
Nor ubuntu 19

**Comment by safesurfer** [comment]
It is resolved and Moving it to Done. QA verified on Ubuntu
