### ISSUE TITLE
Browser should request relative resources from _same_ version of site

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe_browser#1010]
Steps to reproduce:
- create a site with an image & an index.html which will display that image on the site.
- edit that site & upload a different folder with different files or images.
- scroll back to the previous version - the original image you uploaded will not display

![image](https://user-images.githubusercontent.com/37112040/66131156-cdd66a80-e5ea-11e9-8985-203f3eb36a67.png)

Using the cli we are able to use `cat` and see/download the image still, so it is there, however the browser is not rendering it any longer

**Comment by joshuef** [comment]
There are a few things to note here:

@S-Coyle , the site uploaded doesn't point to a root for that image. `<img src="CelticBadge.jpeg" alt="badge">`, should have `<img src="/CelticBadge.jpeg" alt="badge">` to render. Doing so throws another error though as that would _always_ point to the _latest_ version of this site (as unversioned) (without a specific version in the URL for now). Which, as it stands, does not have the image.

 The main thing to sort here is this relative rendering of contents. (ie, with the missing `/`)

- [ ] Relative contents _should_ come from the same version.

**Comment by calumcraig** [comment]
Testing this against `v0.15.2-RC2`. Can now flick between completely different versions of the same URL and images maintain their integrity:
v1
![image](https://user-images.githubusercontent.com/44327924/67218763-d8806480-f41e-11e9-93da-d892b5b7e564.png)
v2
![image](https://user-images.githubusercontent.com/44327924/67218800-e59d5380-f41e-11e9-920e-c76944f44286.png)
v3
![image](https://user-images.githubusercontent.com/44327924/67218843-f4840600-f41e-11e9-9e4f-66157f097b69.png)

(If cycle back through versions the pages all display correctly.)

QA verified, moving this to done.
