### ISSUE TITLE
Browser should block resources from unversioned external urls

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#1029]
As per comment: https://safenetforum.org/t/so-you-want-to-make-a-safe-website/29709/21?u=joshuef

site : `safe://a` shoudl not load resource from `safe://b` if they are unversioned

**Comment by theWebalyst** [comment]
An wondering about the UX here and not sure it makes sense for all external links to be versioned. Let's say you link to a Wikipedia page, or the front page of a news site.

I'm some cases tool want to send people to the latest version, in others to a particular version. So I don't think blocking is a good idea. It's like forcing all external links to go to a page frozen in time in the internet archive.

I'm not sure how we handle this to give a good UX. There could be a hint such as a different colour in the address bar asking with an info icon so you can find out what this means. Thoughts?

**Comment by joshuef** [comment]
@theWebalyst to clarify: this does not require all links to sites to be versioned.

It requires resources loaded as part of a pge to be versioned.

ie: you site `safe://happy` loads some css from `safe://css-reset`. If that is _not_ versioned (and we allow it to load), the owner of `safe://css-reset` can make changes to the CSS which will affect your site, without a record of those changes (nor any way to revert to a previous state).

So _that_ is blocked.

This does not talk about linking to other pages. (which are effectively updating the address bar). Nor does it block loading of non versioned resources via the APIs. 

So you _could_ load `safe://css-reset` via javascript eg. But the initial javascript for _this_  (on the page) will be versioned.

**Comment by joshuef** [comment]
To further clarify: if a page makes a request and it's not from the same hostname as the webview element, and its not versioned. we block it.

**Comment by calumcraig** [comment]
See notes for testing in issue #1052 

This is now working as expected.

QA verified, moving this to done.
