### ISSUE TITLE
Windows version of SAFE browser does not resolve some sites

### ISSUE THREAD

**Issue by JPL1** [maidsafe/safe_browser#1031]
In the Windows 10 version of the Browser (the one launched by SAFE Network App) sites such as safe://dweb and safe://solid-filemanager do not resolve. Instead the HTML code is displayed. However, these sites work fine on Linux (Ubuntu 19.4).  I think dweb was created using React Static. Not sure about solid-filemanager.
![windows-safe-browser-dweb](https://user-images.githubusercontent.com/12783198/66743432-c8421580-ee71-11e9-82d8-3f6401c85448.PNG)

**Comment by joshuef** [comment]
Superseded by #1061 .

But just FYI, @JPL1 this appears to be happening as the content type of those uploads is `null`, not sure where/how that got applied. So we'll be looking to see if this happens with uploads with latest CLI first I think.

More info in the other issue 

Thanks for reporting!
