### ISSUE TITLE
Creating a new site with Browser leads to 404 error

### ISSUE THREAD

**Issue by JPL1** [maidsafe/safe_browser#1126]
Previous error #1119 has been fixed but the browser still does not allow the creation of a site.

Steps:

Download SAFE Browser v0.15.4.beta.2 Appimage
Start safe-authd
Start CLI and login
Start SAFE Browser
(EDIT: logging in and lanching brower from SNAPP  makes no difference)

Enter nonsese URL safe://frwer3r3ssdd
"Nobody owns this address yet"
Click on Register safe://frwer3r3ssdd
Click on Create site
"404 Not found"

Windows 10 and Ubuntu 19.10
Shared vault
v0.15.4.beta.2

**Comment by joshuef** [comment]
Aha, @JPL1 I think you're missing the auth request in whatever form of authd you have running. This would lead to the browser auth timing out, and then an attempt to load an emtpy page.

ATM SNAPP does _not_ jump into focus with auth requests, so you'll need to manually focus the app to auth the request.

Equally, with the command line authd, you have to manually trigger 'accept', which is best done via watching the authd logs (for me: `tail -f $TMPDIR/safe-authd.out`, and getting the request ID, and then running `safe auth allow <request-id>`.

**Comment by joshuef** [comment]
Closing as non-issue as per above. Happy to reopen if that isn't working.
