### ISSUE TITLE
GitHub Action for pushing release files to S3 is not working

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe_browser#1155]
This did work previously, but now results in the error:
```
##[warning]Failed to download action 'https://api.github.com/repos/actions/aws/tarball/master'. Error Response status code does not indicate success: 404 (Not Found)
```

For example of failure see https://github.com/maidsafe/safe_browser/commit/a05960ca66d2866249d781ee0b31626e70f32b74/checks?check_suite_id=412293412#step:1:10

**Comment by joshuef** [comment]
Fixed in https://github.com/maidsafe/safe_browser/commit/1413e4ba4e0a50baecc2810eacdc87e2c7c1fa73
