### ISSUE TITLE
Upload a static web using the browser

### ISSUE THREAD

**Issue by wuniversales** [maidsafe/safe_browser#1167]
Would it be possible to upload a static web graphically using the browser?
I think it would be a very useful function for everyone, at least I would use it.

**Comment by joshuef** [comment]
@wuniversales you can already use the interface to do this (via uploading a folder): https://safenetforum.org/t/so-you-want-to-make-a-safe-website/29709

Or what are you meaning with 'graphical'?

We do already have plans on a more interactive approach to this, but it will be a while before we get to it.
