### ISSUE TITLE
Routing issues with a clean static website (safe://dweb built with ReactStatic)

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe_browser#1188]
## Context
Today I used the latest SAFE CLI to create and upload `safe://dweb` blog to the recently reset shared vault. Only the initial upload has been performed, so everything is at version zero.

Using SAFE Browser 0.16 alpha2, the home page loads as expected, and I can use the page navigation links to visit various pages without errors.
## Problem 1
While navigating `safe://dweb`, as soon as I use the browser back button I get a 404 error. Note: the identical website works fine on the web (http://dweb.happybeing.com).

## Problem 2
If you note some of the URLs for pages while successfully loading them and enter any of these manually later, it gives a 404. Every page I've tried to load via the address bar gives a 404 - except for the home page at `safe://dweb` which always loads ok. Note: the identical website works fine on the web (http://dweb.happybeing.com).

## Steps to Reproduce (for bugs)

1. Start SAFE Browser 0.16 alpha.2

2. Visit `safe://dweb`

3. Click 'Blog' link and the page will load ok. Click around different links and they work ok (including the '< Back' navigation link on a blog post).

4. Use browser back button and it gives a 404 error.

5. At any point try entering valid page URLs into the address bar such as `safe://dweb/blog` (with or without trailing slash) and you get a 404.

6. At any point, enter `safe://dweb` and the home page will load ok.

Note: the identical website works fine on the web (http://dweb.happybeing.com).

## Your Environment

- Operating System and version: Ubuntu 19.04
- SAFE Browser 0.16.alpha2
- shared vault `safe://dweb`
- github: https://github.com/theWebalyst/dweb-blog

**Comment by theWebalyst** [comment]
Just to add - the browser back button **works** on SAFE mobile browser v0.3.0 on Android, so this issue applies only to SAFE desktop browser.

**Comment by S-Coyle** [comment]
Verified as resolved in new [v0.16.1-beta.0](https://github.com/maidsafe/safe_browser/releases/tag/v0.16.0-beta.0) - only tested on macOS so far
