### ISSUE TITLE
async / await not working in Windows build

### ISSUE THREAD

**Issue by Mindphreaker** [maidsafe/safe_browser#124]
Operation System: Win10
Beaker Version: https://github.com/maidsafe/safe_browser/releases/download/0.4.0/safe-browser-v0.4.0-win-x64.zip

The following line throws an error (easily reproduceable when executed in the console):
(async () => { console.log('test'); })();

Error:
Uncaught SyntaxError: Unexpected token (

However it seems to work under linux:
https://forum.safedev.org/t/probably-promise-overuse/881/10?u=mindphreaker

**Comment by hunterlester** [comment]
https://forum.safedev.org/t/probably-promise-overuse/881/13?u=hunterlester

**Comment by bochaco** [comment]
This is working as expected with latest code from browser's master branch.
