### ISSUE TITLE
Missing "range" argument in safeImmutableData.read

### ISSUE THREAD

**Issue by loureirorg** [maidsafe/safe_browser#13]
According to [API docs](https://api.safedev.org/low-level-api/immutable-data/read-immutable-data.html), we should be able to pass a byte range to [safeImmutableData.read](https://github.com/joshuef/safe-js/blob/master/src/immutable_data.js#L63).

--
_Operation System: Linux 4.4.0 - 64 bits (Ubuntu 16.10)
Beaker Version: 0.4.3-lunux-x64_

**Comment by krishnaIndia** [comment]
You can switch to the [new APIs]( http://docs.maidsafe.net/beaker-plugin-safe-app) from now on. Here is the [API for reading immutable data](http://docs.maidsafe.net/beaker-plugin-safe-app/#windowsafeimmutabledataread)
