### ISSUE TITLE
CONNECTION FAILED Could not connect to the network There was an problem with the network connection.

### ISSUE THREAD

**Issue by discapacidad5** [maidsafe/safe_browser#1369]
install the latest version of the browser on Windows 0.18.4 alpha5
The installation was done correctly but when I finished the installation and opened the browser, it showed me the following message.

CONNECTION FAILED
Could not connect to the network
There was an problem with the network connection. 

## Prerequisites

- [ ] Using yarn
- [ ] Using an up-to-date master branch
- [ ] Link to stacktrace in a Gist (for bugs)

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version :
- Link to your project :

**Comment by S-Coyle** [comment]
@discapacidad5 There's currently no live running network for the browser to connect to, hence the error you are seeing.

The next iteration of the network is being worked on and we hope to have available in due course. Once it is available, it would initially be with a CLI interface (i.e. https://github.com/maidsafe/sn_api/releases ) but we would then look to update the browser, and other apps, to be compatible.
