### ISSUE TITLE
State apparently not saved

### ISSUE THREAD

**Issue by JPL1** [maidsafe/safe_browser#150]
Operation System:
Win10
Beaker Version:
0.5.0

Selecting Save Browser State or Save Browser State and Close doesn't seem to do anything. On restarting no open tabs or history are saved. The browser is authenticated.

**Comment by frabrunelle** [comment]
Yes, this was listed as a known limitation in the [dev update](https://safenetforum.org/t/maidsafe-dev-update-august-31-2017-test-19/15974):

> There is a known issue with saving the browser’s state on the network which we expect to fix shortly and provide a patch for the browser with this fix ([MAID-23183](https://maidsafe.atlassian.net/browse/MAID-2318)).

It should be fixed in the next release of SAFE Browser 🙂

**Comment by JPL1** [comment]
Ah OK.
