### ISSUE TITLE
SAFE Browser doesn't loads correctly (javascript error)

### ISSUE THREAD

**Issue by werewere** [maidsafe/safe_browser#152]
Operation System: Mac Os X 10.10.5
Beaker Version: 
SAFE Browser version: 0.5.0

As soon as I start the browser, it gives me a javascript error. Then, when I go to the Authenticator, it gives another error "Failed to load library". I attach screenshots of both.

<img width="1247" alt="captura de pantalla 2017-09-05 a las 18 04 17" src="https://user-images.githubusercontent.com/8255075/30070769-ce3cb280-9264-11e7-8faf-c76e1bc44fd8.png">
<img width="492" alt="captura de pantalla 2017-09-05 a las 17 59 19" src="https://user-images.githubusercontent.com/8255075/30070770-ce537150-9264-11e7-9849-f2bbf73058d7.png">

**Comment by bochaco** [comment]
It seems you are trying to build the browser yourself, is this correct?
If so, please pull the latest code from the browser's master branch, set the env var `NODE_ENV=dev`, then run `yarn run burnthemall`. After that you should be able to use the browser with mock by launching it with `yarn start`.

**Comment by werewere** [comment]
No, I'm afraid I just downloaded the .dmg binary, safe-browser-v0.5.0-osx-x64.zip

**Comment by bochaco** [comment]
The error you see is when you have a browser trying to connect to the mock but the safe_client_libs libraries are built for the network, so it's quite strange you get that with the package you download from our releases page. 
Can I ask you to please download the package again, making sure you remove any other one you downloaded before. 
I just tried by downloading https://github.com/maidsafe/safe_browser/releases/download/0.5.0/safe-browser-v0.5.0-osx-x64.zip and I was able to launch it without any problems on OS X 10.12.4.

**Comment by werewere** [comment]
I downloaded it again from your link, same error... Are there implemented some browser starting debug commands? I could try to debug it a bit.

**Comment by werewere** [comment]
I was going to download the build environment to build the browser, but actually I think it is a better idea if I avoid to do it; may be that the build lacks some library that is already included in the development environment, and that's why it works for you, but not for me. So to find the problem may be it is better if I keep my computer "clean" without development files.

In the past I found this problem a couple of times; Other colleagues and me developed a specific piece of software and it worked for all of us, but another guy who hasn't got the development environment was unable to make the binaries work. May be it is somehow related to this :?

**Comment by bochaco** [comment]
I'm not an OS X user, I just happened to have a friend here to try it out. From my understanding there shouldn't be any need of anything else for OS X, I can tell that the Mac where I tried never had anything installed/run related to the SAFEnet for sure. I'll ask some of the other guys who does work with Mac to try to help here.

**Comment by joshuef** [comment]
I've tried this on a fresh OSX (10.12.5) computer (ie, not mine so no trace of SAFE things), and couldn't reproduce the errors here. Everything worked as expected.

@werewere have you had any success with a previous version of the browser before?

**Comment by werewere** [comment]
Very good idea @joshuef, I've downloaded the previous version, safe-browser-v0.4.0-osx-x64 and... it worked correctly. Then, after starting v0.4.0, I closed it, and tried again to start v0.5.0, and again the problem appears. Then, just to test another one, I downloaded and executed safe-browser-v0.3.0-osx-x64, and it also works.

So it seems that the only one failing is this version, 0.5.0

**Comment by joshuef** [comment]
Hmmm, well that makes it look like a bad build. I've no idea how you're getting a bad build from the download link for OSX, as it works on other tests (unless it's an OSX version issue.. but again not sure how much affect that would have...)

Just to triple check. Can you make sure your downloads folder has no version of the safe browser in it, and neither your applications folder. And then could you try once more downloading the link @bochaco provided, but in chrome or safari incognito/private browsing mode (depending on what you normally use). Just incase there's some caching problem going on here...

**Comment by werewere** [comment]
Yep, same problem. I downloaded it with a private tab in a browser that I never use (Firefox), but still it shows the same error after unzipping.

**Comment by bochaco** [comment]
@werewere , can you please try with the new version we just released for the browser (v0.5.1) to see if you are still facing the same problem. If you do, then we should get a better description of the error message in that pop-up which should help us to move forward. 
If the new version doesn't work for you, we are planning to schedule a hang out session with you to try to troubleshoot this on your Mac. So please let us know how it goes.

**Comment by werewere** [comment]
It works now with v0.5.1! Problem fixed :)  Thanks for your help, I'm really excited about this project!

**Comment by bochaco** [comment]
great! thanks a lot @werewere for your help!
