### ISSUE TITLE
'full screen' option in HTML 5 video control doesn't seem to work

### ISSUE THREAD

**Issue by wardbr** [maidsafe/safe_browser#157]
Operation System: Windows 10 and Linux Mint 18.2
Beaker Version: 0.5.1

When clicking on the Fullscreen toggle in the lower right of the video control (using attribute controls in the HTML5 video element), the video doesn't go in full screen. E.g. on youtube when SAFE Browsing is disabled.

**Comment by hunterlester** [comment]
Thank you @wardbr, we'll check it out.

**Comment by hunterlester** [comment]
This issue has been solved with our new browser, https://github.com/joshuef/peruse.

I tested successfully with Peruse, running a local website containing an HTML5 `video` tag.
