### ISSUE TITLE
Buffer not accessible

### ISSUE THREAD

**Issue by josephm1** [maidsafe/safe_browser#174]
Operation System: Windows 8.1
SAFE Browser Version: v0.5.2
The Buffer is not accessible in javascript from the browser, this means websites like Demoy and Vidy can't work as they need that function to convert files into a suitable format for the SAFE API. To test type 'Buffer' in the console and you'll get an error `VM127:1 Uncaught ReferenceError: Buffer is not defined
    at <anonymous>:1:1` but if you type in 'History' you will get its proper function back.

**Comment by hunterlester** [comment]
Right, only NodeJS supports the `Buffer` object.

In the browser you can use utilize the [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) along with one of the [TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) objects.

Typically we are working with `Uint8Array`, https://github.com/maidsafe/safe_examples/blob/master/safe_web_api_playground/static/js/code-snippets/safeMutableDataEntries.js#L19

**Comment by bochaco** [comment]
@hunterlester , @josephm1 , I closed this one as I understand this is not a bug.
