### ISSUE TITLE
Safe Browser : too long a file name error

### ISSUE THREAD

**Issue by wrnice** [maidsafe/safe_browser#175]
Operation System: linux x64, fedora 21
Beaker Version: 0.5.2 ( and 0.5.1 too )

When I try to authenticate applications ( web hosting manager or mail tutorial ) , the browser opens an error popup, complaining that some file name is too long : 

`/home/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/safe-browser-v0.5.2-linux-x64/safe-mv0lm1hawrzywzllndlymhvc3rpbmdtyw5hz2vy:AQAAAIZq7s4AAAAAAAAAACAAAAAAAAAANhKBvmBtLdgG1kiQwykWzc5GNbckkhS9cQuQONDQgVUgAAAAAAAAAFMi2_wOrvvwjAsVIuQVq7dqxuP4lQMa8PdXKuHa5Gc6IAAAAAAAAADsJhE_taL3AXgl4gEJIMNqhhWorQvskhclEBp0j9b4EUAAAAAAAAAAlwH8pBnd2tDr2T7GFWtGhxi1XV615K2MYyQswlU1htXsJhE_taL3AXgl4gEJIMNqhhWorQvskhclEBp0j9b4ESAAAAAAAAAA3-B59To-0oJqtlGJfisNVjXOjBugd47L7W1YE7Wl5HAgAAAAAAAAAC7ukZZn6EeBMwo1xjwNUeubpfjs7PcGLMSY3HaATHeUGQAAAAAAAAASAAAAAAAAADQ2LjEwMS40Mi4yMDU6NTQ4MxIAAAAAAAAANDYuMTAxLjYxLjIzNjo1NDgzFAAAAAAAAAAxODguMTY2LjE0NC4xODQ6NTQ4MxQAAAAAAAAAMTg4LjE2Ni4xNTMuMjI3OjU0ODMTAAAAAAAAADE4OC4xNjYuMTc1LjgwOjU0ODMUAAAAAAAAADE4OC4xNjYuMTc1LjEwOTo1NDgzFAAAAAAAAAAxODguMTY2LjE3NS4xMTA6NTQ4MxQAAAAAAAAAMTg4LjE2Ni4xNzUuMTEzOjU0ODMUAAAAAAAAADE4OC4xNjYuMTcwLjIzNTo1NDgzEwAAAAAAAAAxMzkuNTkuMTYwLjExOTo1NDgzEwAAAAAAAAAxMzkuNTkuMTc1LjIyNTo1NDgzEwAAAAAAAAAxMzkuNTkuMTYyLjEyOTo1NDgzEgAAAAAAAAAxMzkuNTkuMTYzLjg0OjU0ODMTAAAAAAAAADEzOS41OS4xNjMuMTMwOjU0ODMSAAAAAAAAADEzOS41OS4xODAuNDc6NTQ4MxIAAAAAAAAAMTM5LjU5LjE4OC4yNzo1NDgzEwAAAAAAAAAxMzguNjguMTMzLjEyNDo1NDgzEwAAAAAAAAAxMzkuNTkuMTgxLjE5NTo1NDgzEwAAAAAAAAAxMzguNjguMTUyLjE1MTo1NDgzEwAAAAAAAAAxMzguNjguMTQ4LjEwNDo1NDgzEwAAAAAAAAAxMzguNjguMTY4LjE4MDo1NDgzEgAAAAAAAAAxMzguNjguMTY5Ljk3OjU0ODMTAAAAAAAAADEzOC42OC4xNjkuMTYxOjU0ODMTAAAAAAAAADEzOC42OC4xNjkuMTY1OjU0ODMTAAAAAAAAADEzOC42OC4xNjkuMTkwOjU0ODMBaxUAAAAAAAEPAAAAAAAAAHRlc3RfbmV0d29ya18xOQBYkv7M4jz4ko7XdY1u33mLT67kCzuWqo09-76qKGOyWpg6AAAAAAAAGAAAAAAAAAD3EAdII0BkSDkpzRUxC82nWegKC5XsxGE=: File name too long`

it seems to reproduce always.

**Comment by wrnice** [comment]
ah, in fact the error popup^is not from Safe_browser, but from pcmanfm, the file manager in lxde.
When using safe_browser for the first time, it creates an entry for the browser  in the lxde menu. If I delete this entry, and try to authenticate an app, when I click "allow", it opens a blank firefox window instead of the error message.
So, I have a feeling that when I click "allow" in the browser, the message is sent not to the app that requested it, but instead to the window manager or something like that.
I notice this behaviour started when I uninstalled the fedora repo firefox to update it by a manually installed up-to-date firefox .

I'll keep digging into that direction...

**Comment by bochaco** [comment]
Hi @wrnice , it seems you have issue with the URI scheme, perhaps you can clean up your URIs registered for `safe` and `safe-auth` protocols. I'm not sure where they are in Fedora, as an example in Debian they are under `~/.local/share/applications/`. After that, launch the browser so it registers them again and then run the apps.

**Comment by wrnice** [comment]
hello ! Yes, I had thought about this ,it seems to me that pcmanfm is trying to handle what should be handled by the safe app. 
I tried to delete everything related with safe in .local/share/application. When I relaunch the browser and try again, it does just the same. 
there must be something screwed with my mime types somewhere

**Comment by wrnice** [comment]
Hello !
I tried again and again to cleanup my URI schemes handling, with no avail. 
So I tried : 
1 ) creating a fresh user on the same machine, downloading and starting the safe_browser and the web_hosting_manager : the result is just the same : pcmanfm throws an error about a file name too long
2 ) downloading and starting the browser and hosting manager on another machine that has a fresh fedora install : result is exactly the same.

( at least it seems my uri handling is fine :) )

So I am having the impression that there is something else here. How about this resides in my current test 19 account ?
This reminds me an issue in the past, where some special characters in some keys caused problems in authenticating - I'll try to find the links in the forum and paste it here asap.

**Comment by wrnice** [comment]
still no luck with alpha2, just tried on a fresh fedora 26 install , fresh user -> same result :  

pcmanfm tries to handle the authentication response from the authenticator, spits an error for a file too long, and the app hangs here.

I'll try with a fresh debian right now.

**Comment by bochaco** [comment]
Thanks @wrnice . I'm closing this since we are not supporting many desktop environments for the moment, like LXDE.
