### ISSUE TITLE
Unable to build for production

### ISSUE THREAD

**Issue by cooperka** [maidsafe/safe_browser#176]
### Issue

I can't seem to build for production from source anymore, just dev.

I think it worked a few weeks ago, and the [released binary](https://github.com/maidsafe/safe_browser/releases/tag/0.5.2) works just fine.

### Attempted solution

1. `export NODE_ENV=prod`
2. `yarn run burnthemall`
3. `./dist/linux-unpacked/safe-browser`
4. Attempt to sign in
    - `Core error: Unexpected: Could not connect to the SAFE Network`

### Questions

1. Is there a different method I should be using to build, or is this a bug?
2. How can I quickly check whether my app is compiled for `dev` or `prod`? e.g. when I run the SAFE Browser, does it show this anywhere?

### Versions

- OS: Ubuntu 16.04
- safe_browser version: [master@{2017-09-17}](https://github.com/maidsafe/safe_browser/commits/master@%7B2017-09-17%7D)

**Comment by bochaco** [comment]
You must be missing the crust cobfig file. Make sure you copy the `safe-browser.crust.config` file onto `./dist/linux-unpacked/`, you can get a copy of it from the package we released.

**Comment by cooperka** [comment]
Excellent, that was all that was needed. Would you like me to add this step to the README?

**Comment by bochaco** [comment]
Great!
We are working on making that to be done by the packaging script, so we won't need to do that manually, thus I don't think we really need it in the README.

**Comment by cooperka** [comment]
Sounds good, thanks @bochaco.
