### ISSUE TITLE
Address bar selection issue

### ISSUE THREAD

**Issue by Mindphreaker** [maidsafe/safe_browser#181]
Operation System: Win10
SAFE Browser Version: 0.5.2

When clicking into the address bar the whole URL text is selected (so far so good). If I click a second time, nothing happens. Normally it should deselect the URL and put the cursor at the end of the URL. This is very annoying as it makes it hard to add something to the URL.

Note: This issue appears to be sproadic but happens almost everytime (estimated 29 of 30 times).
Ps.: I don't think this happened in earlier versions.

**Comment by Mindphreaker** [comment]
Just wanted to add, that this is still present in SAFE Browser v 0.5.3

**Comment by joshuef** [comment]
> Normally it should deselect the URL and put the cursor at the end of the URL. 

I think this behavior should put the cursor wherever in the text you clicked? (And if you click at the end/rest of address bar, it would go to the end).

But if I understand you correctly, the whole line is still highlighted upon a second click anywhere in the address bar?

If you press the right arrow key, after clicking does the address bar 'dehighlight' and the cursor move as expected?

**Comment by Mindphreaker** [comment]
Yes @joshuef exactly. After I press the right key it gets dehighlighted and the cursor moves to the end of the url. Afterwards the click / cursor behavior works as expected.

The bug only occures if the whole url is selected. If only parts of the url are selected, the cursor behavor works too. I hope this helps. Let me know if you need any more information.

**Comment by joshuef** [comment]
Okay, I can see what you're talking about on win. 

It's the same behaviour as the other platforms, but appears to be a bit slower. Either way we probably want better address bar highlighting for URL portions as well anyway (how most other browsers handle it). So hopefully we can tackle this/that together 👍

**Comment by Mindphreaker** [comment]
> It's the same behaviour as the other platforms, but appears to be a bit slower.
I'm not 100% sure what you mean with the above. In my case it isn't just slower, the click event doesn't work at all (most of the time) when everything is highlighted.

Because it's hard to describe I've made a video showing the behavior (turn on sound to hear when I click):
https://uploader.tinytake.com/sf/MTk3MzUyMF82MjQ5MTgz

As you can see, sometimes it works as expected, but most of the time not. Hope this helps.

**Comment by Mindphreaker** [comment]
Okay, just tested it on another Win10 system and there it works without any problems. I now think it could have to do with the other systems 2k screen / resolution in combination with Win10 scaling feature. Will try to verify this and report back.

**Comment by bochaco** [comment]
We are not working on this fix yet as this issue is not reproducible on Peruse (the new custom browser currently under development) so we will just wait until Peruse is ready and close this bug at that point in time. We are at the moment only fixing critical issue on the SAFE Beaker browser.

**Comment by hunterlester** [comment]
So far testing our new browser, https://github.com/joshuef/peruse, on Windows 10 I don't have the address bar selection issue like I do with SAFE Browser.
