### ISSUE TITLE
Non-null value for "tcp_acceptor_port" parameter

### ISSUE THREAD

**Issue by Thierry61** [maidsafe/safe_browser#188]
Operation System: Windows 10
Beaker Version: 0.6.0.0

safe-browser.crust.config file has a non-null value for "tcp_acceptor_port" parameter (5483). I would understand this value for a vault. But for a client program that seems a bit unsafe.

If there isn’t any reason for this value, then I suggest putting back the null value for this parameter.

**Comment by hunterlester** [comment]
Thank you for helping us by inputting this concern.
Tasked for review: https://maidsafe.atlassian.net/browse/MAID-2372

**Comment by bochaco** [comment]
This is fixed in beaker browser v0.8.1.
