### ISSUE TITLE
Link from [Claim and Invitation] to Firefox in Linux, doesn't work, if the browser is not already open.

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_browser#189]
Operation System: Linux Min 18.1
Beaker Version: v0.6.0-linux-x64

Link from [Claim and Invitation] to Firefox in Linux, doesn't work, if the browser is not already open. If it's not open, then clicking the button sees Firefox starts but its frozen; not obviously putting any url to the url-bar; and requires force quit.

**Comment by joshuef** [comment]
This works fine in Ubuntu 16, I wonder if this isn't a linux min issue as all the browser is doing is triggering the system to open the url with whatever program is defined for this.

**Comment by joshuef** [comment]
Closing as I couldn't replicate this and we don't currently support Linux Min.
