### ISSUE TITLE
Assurance build

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_browser#191]
Operation System: Linux Mint 18.1
Beaker Version: safe_browser-alpha-2 source code

I wondered it would be good to tighten the build detail, enough that someone can fairly push buttons and get assurance against the declared SHA-256.. unless that limited to validating the download only for some necessary variance on builds.. but I'm expecting that the SHA-256 should be the output of all builds of the same form.

So, two errors follow beyond simply updating the build software:

```error https://s3.eu-west-2.amazonaws.com/beaker-plugin-safe-app/beaker-plugin-safe-app-0.3.0.tgz: Fetch succeeded for undefined. However, extracting "https://s3.eu-west-2.amazonaws.com/beaker-plugin-safe-app/beaker-plugin-safe-app-0.3.0.tgz" resulted in hash "93ff8377180dc84c046b8598a15b9cd61190437a", which did not match the requested hash "496a9b46ffc32e050a5a636629dc4bd23d656de5".```

Seems to suggest perhaps the source is not stable enough for assurance build, where there perhaps beaker-plugin is evolving.

then, npm install fails against ~
```npm ERR! undefined postinstall: 'cd app && yarn install && cd .. && yarn rebuild'```

which I don't understand..

-----
to note: for others passing by, the update of software seems to be simply:

Install of "yarn", available from https://yarnpkg.com/en/docs/install#linux-tab

Instruction to update npm seems to be:
> npm install npm@latest -g

Instruction to update node seems to be:
> sudo npm cache clean -f
> sudo npm install -g n
> sudo n stable

**Comment by joshuef** [comment]
@davidpbrown yeh, that first error should be avoided on our end. I think it slipped in as a consequence of the A2 push. Somewhere we hadn't updated yarn.

This is being straightened out and we're working towards automating the build process much more so these sorts of error should be caught and wont make it into master 👍 

-----

For the second error, I take it you didn't have `yarn` installed?

**Comment by davidpbrown** [comment]
No - I've done the obvious and installed yarn, which is why it was a surprise.. I can't make sense of what it's suggesting.

**Comment by bochaco** [comment]
I'm closing this as this should have been a one time thing as suggested above when we didn't update the yarn.lock files on the master branch after updating our plugins packages ending up with different hashes. We now have CI scripts to run automatic test with each browser's PR which will prevent this from happening again.
