### ISSUE TITLE
Browser froze

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_browser#200]
Operation System and Version: Linux Mint 18.1
SAFE Browser Version: v0.6.0
Network: Alpha2
Description: With only browser open, visiting safe://thewall the browser froze where it had been working and then was entirely unresponsive, including the window's [x] close button. It seemed to be timed when I was selecting object of sponge but expect perhaps that was coincidental as it's not been a problem previously. Moving the window border then made for a different type of art and evidenced that is was frozen. The view behind the browser then is desktop and the terminal, which didn't report anything of this event.
Steps to reproduce: unknown but I've got whatever is produced into logs, if those might help. Let me know what those are that are useful.. or I can try again but don't want to loose any logs that are useful.

![screenshot](https://user-images.githubusercontent.com/1708690/31151103-f858b494-a88d-11e7-9e51-ecf4bd79b95b.jpg)

**Comment by joshuef** [comment]
@davidpbrown can you share your logs please. 

I'd guess something in the site triggered a function which hung, causing the browser process to die. 
We've got plans to move calls to the network to a new process which should eliminate such things, but just to see what we can see if you can share them here, that'd be grand thanks. 👍

**Comment by davidpbrown** [comment]
Not sure what is useful; so, I'll upload *.log

[libpeerconnection.log] is empty.

[SAFE_Browser.MaidSafe.log](https://github.com/maidsafe/safe_browser/files/1356635/SAFE_Browser.MaidSafe.log)

[authenticator.log](https://github.com/maidsafe/safe_browser/files/1356628/authenticator.log)

**Comment by joshuef** [comment]
Have you been able to reproduce this reliably @davidpbrown ? 

I don't see anything obvious in the logs...

**Comment by bochaco** [comment]
Verify if this is also an issue in Peruse v0.7.0, otherwise let's close it.

**Comment by hunterlester** [comment]
Navigated to `safe://thewall` with the `peruse` branch of this repo. Working nicely. No freezing.
