### ISSUE TITLE
 Favourites are lost after quitting and restarting SAFE browser

### ISSUE THREAD

**Issue by lubziw** [maidsafe/safe_browser#202]
Operation System and Version: MacOS Sierra version 10.12.6
SAFE Browser Version: Version 0.6.0 (0.6.0)
Network: <Testnet, Alpha, Mock> Alpha 2
Description:  Favourites are lost after quitting and restarting the browser
Steps to reproduce: <Please be as detailed as possible here, include a link if you have an example on the network.>
- open browser
- favourite a website
- check favourites, website is added
- quit browser
- launch browser
- favourites dissapeared

**Comment by joshuef** [comment]
@lubziw are you saving the browser state to the network (currently this needs to be done manually).

So you'd need to log in to the network, and then `cmd-shift-s` (or access via the `file` menu dropdown), to save the state.

Then when you quit / restart, after you log back in the favourites should show up.

**Comment by lubziw** [comment]
Retested after saving the state. Passed.
