### ISSUE TITLE
Safe Browser is crashing

### ISSUE THREAD

**Issue by diegomr86** [maidsafe/safe_browser#203]
Operation System and Version: Ubuntu 16.04
SAFE Browser Version: SAFE Browser v0.6.0
Network: Alpha 2 with mock
Description: Safe Browser is crashing 
Steps to reproduce: I'm developing a web app using the DOM API but the browser is crashing and I can't find a log. There is any way to check the logs to see the reason of these crashes?

**Comment by luandro** [comment]
Same with MacOS Sierra.

**Comment by joshuef** [comment]
@diegomr86 Can you please post some steps to reproduce, ideally with an example app.

----

You can see safe network logs via the `file` menu dropdown. But that is only network interactions. You may be having other errors related to your js code or the browser, I can't tell without some sample code.

**Comment by hunterlester** [comment]
@diegomr86 @luandro Thank you for reporting. I'm experiencing the same intermittent crashes on Windows 10.
Haven't found any patterns yet.
@joshuef I'll try to get it to crash and then share my logs.

**Comment by diegomr86** [comment]
Hi @joshuef, this is the steps I followed:

Install and run the safe browser

git clone https://github.com/maidsafe/safe_browser.git
cd safe_browser
NODE_ENV=dev yarn
yarn run build
yarn start

Run the app
git clone git@github.com:MoinhoDigital/safewallet.git
cd safewallet
yarn
yarn dev

Access the app and authorize in the safe_browser:
localhost://p:3000

After some navigation or refresh the browser crashes seemingly randomly.

**Comment by diegomr86** [comment]
The browser is still crashing making impossible to work with it.

**Comment by hunterlester** [comment]
There are two types of crashes that I'm experiencing, one where the browser hangs and then closes altogether, and the other where the browser window turns black and greys out dev tools, if open.

The former is seemingly random, and the latter is consistently reproducible.

I'm wondering if they are both related to the many issues being reported by the Rotande and Beaker communities, all rooted in electron: https://github.com/electron/electron/issues/9342

**Comment by bochaco** [comment]
This has been solved in Peruse v0.6.0 already.
