### ISSUE TITLE
URL.createObjectURL(blob) hangs the page

### ISSUE THREAD

**Issue by wrnice** [maidsafe/safe_browser#205]
Operation System and Version: Linux Fedora 26 , x64
SAFE Browser Version:   git master
Network: Mock
Description:  URL.createObjectURL(blob) blanks the window, then the app keeps hanging here
Steps to reproduce: 

```
var blob = new Blob( ["blah blah"], { type: "text/plain" } );
var theUrl = URL.createObjectURL(blob);
console.log ("test",theUrl);
```
a web page with only this code  goes all black, and the 'inspect element' right click menu is not available.

If the console was previously open, it hangs too with the message : "Dev tools was disconnected from the page / Once page is reloaded DevTools will automatically reconnect"

Nothing appears in the terminal from which I launched the browser.

**Comment by hunterlester** [comment]
Thank you for reporting. I've added this to an existing issue that I'm having when attempting to use `readAsArrayBuffer` to read and return file buffer to upload to network.

I added it here: https://maidsafe.atlassian.net/browse/MAID-2257

**Comment by wrnice** [comment]
thanks !  it doesn't *crash* the window, though, just hangs here and idles

**Comment by bochaco** [comment]
As per https://maidsafe.atlassian.net/browse/MAID-2257 this seems to be solved, let's confirm it before closing it.

**Comment by hunterlester** [comment]
Issue resolved!!
Verified by hosting a file via web API playground.
