### ISSUE TITLE
Ctrl-arrow (left/right) for <back> / <forward> breaks some web apps

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe_browser#215]
A quick test in Firefox, Chrome and SAFE Browser show that it is the only one to override Ctrl-<right|left-arrow> and I am finding that this causes it to break web apps which use these within the UI.

Maybe the shortcuts of SAFE Browser need to be more aligned with the standard browsers?

**Comment by bochaco** [comment]
Hi @theWebalyst , can you please provide a webapp as example of this? the SAFE browser is overriding those shortcuts to allow moving back and forth in the browsing history, so we suspect the issue you are actually facing could be due to the webapp not populating the history correctly?

**Comment by joshuef** [comment]
@theWebalyst is this still an issue in Peruse? (I'm assuming this was originally reported for beaker/safe-browser, or?)

I can't replicate in Peruse

**Comment by theWebalyst** [comment]
I've only just seen Gabriel's request sorry.

Josh this was for SB not Peruse.

I don't have an app to try now s it was for the old API.

I suggest we close this. I'll eventually get back to those apps.
