### ISSUE TITLE
mailto: URI scheme not recognized

### ISSUE THREAD

**Issue by rex4539** [maidsafe/safe_browser#227]
Operation System and Version: macOS 10.13.2 (17C60c)
SAFE Browser Version: 0.7.0
Network: alpha_2
Description: mailto: URI scheme not recognized
Steps to reproduce:
1. Have an index.html page with a mailto: URI scheme as a hyperlink.
2. Click on hyperlink.

What happened:
Nothing.

Expected result:
Default Mail client is launched and new message is created with the hyperlinked recipient.

Notes:
Check my website and click the email hyperlink on the bottom -> safe://dimitris.apostolou/

**Comment by bochaco** [comment]
Hi @rex4539 , the SAFE browser only supports the following schemes/protocols:
- `safe:` SAFE websites.
- `safe-auth:` Authorisation requests.
- `safe-logs:` intended only for the browser's own mechanism to open log files.
- `http:/https:` clearnet websites (this is under consideration as there are some security concerns with supporting them)
