### ISSUE TITLE
Yarn does not support Node.js 7.10.0

### ISSUE THREAD

**Issue by petrsnm** [maidsafe/safe_browser#234]
Operation System and Version:  Linux  Ubuntu 16.04
SAFE Browser Version:  
Network: Mock
Description:
Just trying to build the browser following the steps in the readme.md.   Result, a crap-ton of warnings:

warning You are using Node "7.10.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"

Do you need to update the readme.md to recommend a different version of node >=8.0.0 be used?

**Comment by bochaco** [comment]
Thanks @petrsnm !
This is being solved now with PR #242 .
