### ISSUE TITLE
schoolshooting

### ISSUE THREAD

**Issue by aymanalkayali** [maidsafe/safe_browser#259]
Operation System and Version:
SAFE Browser Version:
Network: <Testnet, Alpha, Mock>
Description:
Steps to reproduce: <Please be as detailed as possible here, include a link if you have an example on the network.>

**Comment by aymanalkayali** [comment]
doorlockdown.com new device  to enhance lock down procedure

**Comment by hunterlester** [comment]
Anyone that has come upon this issue, please do not navigate to the url posted above since it has been flagged for phishing.
