### ISSUE TITLE
Missing pack-authenticator

### ISSUE THREAD

**Issue by JPL1** [maidsafe/safe_browser#26]
Operation System: Linux Ubuntu 15.4
Beaker Version:

Compiling SAFE Browser

`user@userVirtualBox:~/safe_browser$ npm run pack-authenticator`
`npm ERR! Linux 4.4.0-75-generic`
`npm ERR! argv "/home/user/.nvm/versions/node/v6.5.0/bin/node" "/home/user/.nvm/versions``/node/v6.5.0/bin/npm" "run" "pack-authenticator"`
`npm ERR! node v6.5.0`
`npm ERR! npm  v3.10.3`
`npm ERR! missing script: pack-authenticator`

Have done a search for pack-authenticator in the `safe_browser-dev ` folder and can't find it

**Comment by frabrunelle** [comment]
What does your `package.json` file look like? Does it contain [this line](https://github.com/maidsafe/safe_browser/blob/f6603a852fc4d4a81e6f1ea62695041bfe551a9c/package.json#L111)?

> "pack-authenticator": "node ./shell_scripts/pack_authenticator.js"

Can you please try to use Git instead and see if you get the same error?

> git clone https://github.com/maidsafe/safe_browser.git
> git checkout dev

**Comment by JPL1** [comment]
Originally no, `package.json` did not contain that line.

However, I tried again and it worked. The only difference between the two tries was the `git checkout dev` command. I didn't use that the first time.

Now it's stuck on updating git repository https://github.com/maidsafe/routing.git ...

Still, progress :)
