### ISSUE TITLE
Ignoring auth requests by clicking `X` prevents further auth requests

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_browser#279]
SAFE Browser Version: head of `peruse` branch

**Comment by theWebalyst** [comment]
That's interesting - are you sure that's SAFE Browser and not Peruse? I think this happened to me with the WebID test build of Peruse this week, but using an earlier official build of SAFE Browser this did not happen.

**Comment by hunterlester** [comment]
@theWebalyst I should have specified `peruse` branch.

**Comment by hunterlester** [comment]
Addressed by PR https://github.com/maidsafe/safe_browser/pull/280
