### ISSUE TITLE
Windows Mock auth failing

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#293]
Testing WebId-MasterMerge branch, when I run browser using yarn mock-dev, it opens the browser in mock mode. When I try to login, it opens another browser window in prod mode. Not able to receive auth request from Peruse. added some log, from terminal for your perusal.
log.txt

(from @safesurfer)

**Comment by hunterlester** [comment]
On Windows, exectuing `WebId-MasterMerge` with `yarn mock-dev`, electron executes but the UI doesn't render.
