### ISSUE TITLE
opening target=_blank does not work

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#294]
target="_blank" doesn't work and does not have the selection to open a link in a new tab as well

**Comment by joshuef** [comment]
on osx a link with `target="_blank"` works as expected.

**Comment by hunterlester** [comment]
@joshuef Confirmed to be working fine on Windows.

**Comment by bochaco** [comment]
So is PR #315 still needed or at least wanted for this @joshuef ?

**Comment by joshuef** [comment]
Yes. It addresses the `does not have the selection to open a link in a new tab ` portion (adding in a simpler/ more flexible contextMenu to boot.)
