### ISSUE TITLE
When running Peruse it freezes on the "Fetching registered apps" screen

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#300]
If Peruse is launched with `yarn prod-dev` then when pressing ctrl+alt+I an error is shown in the browser console but the dev console tool for the current tab is not open:
```
Browser.jsx:99 Uncaught TypeError: activeTab.closeDevTools is not a function
    at EventEmitter._electron.ipcRenderer.on.args (Browser.jsx:99)
    at emitTwo (events.js:126)
    at EventEmitter.emit (events.js:214)
_electron.ipcRenderer.on.args @ Browser.jsx:99
emitTwo @ events.js:126
emit @ events.js:214
renderer.js:34 [17:00:36.316] Uncaught TypeError: activeTab.closeDevTools is not a function
(anonymous) @ renderer.js:34
emitThree @ events.js:136
emit @ events.js:217
renderer.js:34 [17:00:36.317] http://localhost:1214/dist/bundle.js
(anonymous) @ renderer.js:34
emitThree @ events.js:136
emit @ events.js:217
renderer.js:34 [17:00:36.317] 1575
```

**Comment by bochaco** [comment]
This same issue seems to cause the authenticator to freeze on the "Fetching registered apps" screen.
![image](https://user-images.githubusercontent.com/442821/44490776-a36b5d00-a635-11e8-8fa3-b4807601a067.png)

**Comment by joshuef** [comment]
opening devtools was bugging, which I'm sure contributes to the devtools related errors we're seeing.

I'm not sure if that's going to sort the hanging...
