### ISSUE TITLE
Peruse is chopping the `/index.html` when found in the URL you enter which is a problem for the XOR URLs

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#309]
As an example, imagine I have a MD which is not an NFS, if I enter a URL `safe://<MD XOR name>:15002/index.html` the browser is removing `index.html` and the `webFetch` will be fetching the MD that is at that address returning the list of entries (in json format) which would be incorrect since it should have returned a `File not found` error.
We need to agree on what are the responsibilities the browser should take on validating/normalising URLs, if any.

**Comment by joshuef** [comment]
I'd agree @bochaco that it's not the responsibility of the browser to validate / normalise a URL.

Buuuut. There's an arguement for the browser 'hiding' portions of the url for usability. (chrome removes the `index.html` and other default extensions encountered on the web).

So I think that even if we retain the full url info, we could (in some cases) hide that info. And so we should figure out those cases. (Which makes this become a UX issue somewhat, @shankar2105  @JimCollinson  FYI).

If we're agreed on that, I'd keep this issue for discussion of _that_ and we can create another issue for disabling this functionality in the peruse as it is for safe_browser (to keep things simple to start with). Sound like a plan, @bochaco ?

**Comment by bochaco** [comment]
Yes I imagined it was to behave similar to other browsers and I agree we should try that by perhaps separating what it's shown from what it's sent to the underlying lib for fetching. 

But this also made me think if, in a network like SAFE, this type of behaviours should be reviewed as the user is not seeing the exact URL/location the content is being retrieved from, which sounds a bit not so secure or at least for educated users, I'm wondering if we should consider removing all these type of behaviours towards making the new web more secure also from these aspect. These are just thoughts.

**Comment by joshuef** [comment]
https://github.com/maidsafe/safe_browser/blob/peruse/app/utils/urlHelpers.js#L65-L80

```
export const removeTrailingRedundancies = ( url ) =>
{
    let newUrl = url.replace( /index\.html$/, '' );
    newUrl = newUrl.replace( /index$/, '' );
    newUrl = removeTrailingSlash( newUrl );
    newUrl = removeTrailingHash( newUrl );


    // loop until clean
    if ( newUrl === url )
    {
        return newUrl;
    }


    return removeTrailingRedundancies( newUrl );
};

```

We're also removing trailing slash/hash. I'd opt to keep these removed as they (sitting at the end with no text after them), should not be affecting url resolution.

You see any reason to also remove them @bochaco ?
