### ISSUE TITLE
Request: standard browser keyboard bindings

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_browser#310]
Such as: 
- `CTRL + TAB` to move between tabs
- `CTRL + t` to open a new tab
- `CTRL + w` to close focused tab

**Comment by hunterlester** [comment]
Implemented in master branch.

**Comment by theWebalyst** [comment]
Ones I miss:

- Alt-d (synonym for Ctrl-L which is implemented and selects address bar in Chrome and Firefox)
- Ctrl-shift-T (reopen last closed tab)
