### ISSUE TITLE
Peruse does not close properly

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_browser#313]
Migrating issue from joshuef/peruse: https://github.com/joshuef/peruse/issues/100

OS: Arch Linux

Process:

Close the Peruse window by last tab close or window close.

Expectation:

The window closes and the process ends.

Result:

The window closes, but ps -ef | grep peruse shows that the process is still running.

**Comment by S-Coyle** [comment]
We don't think this will be an issue with 0.7.0 - TBC after release

**Comment by hunterlester** [comment]
I've tried several build variations on a Linux VM and on Windows to reproduce this reported bug but am unable to in latest peruse branch as of commit https://github.com/maidsafe/safe_browser/commit/7bb12daf308498252abbbecac3fce6c703a2672c
Passing this along to see if others can reproduce.

**Comment by S-Coyle** [comment]
Tested on MacOS with Peruse 0.7.0 where behaviour is IMO expected to be slightly different - i.e. clicking `x` on MacOS doesn't always close an app, it still has the dot under the icon in the tray. This is the same behaviour as Chrome, FF and Safari.

Right clicking the icon and selecting "Quit" successfully kills the processes for Peruse, as expected, and as is consistent with other browsers.
Note that the processes on MacOS seem to be different to Linux & Windows as the _ps -ef | grep peruse_ command from the original bug report didn't work for me. Investigation found that the processes for Peruse were Electron ones, as pictured below.
![image](https://user-images.githubusercontent.com/37112040/45436448-bb6d5400-b6aa-11e8-8b00-7a60ad3dccec.png)
These processes were all successfully removed when quitting Peruse.

Discussed with @hunterlester who confirmed that all Peruse related electron processes were removed when he quit on Windows.

**Comment by hunterlester** [comment]
@S-Coyle Right. Here's an interesting piece of information to corroborate: https://github.com/maidsafe/safe_browser/blob/peruse/app/main.development.js#L207

**Comment by S-Coyle** [comment]
Verified fixed in Peruse v0.7.0. Closing
