### ISSUE TITLE
Peruse Dev --preload does not work on Linux

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_browser#314]
Migrating from: https://github.com/joshuef/peruse/issues/101

Trying this with Peruse Dev 0.6 I can't get --preload working on Ubuntu 18.

Following the instructions here: https://github.com/joshuef/peruse#debugging I've tried a few ways to start Peruse Dev, including this for example:

NODE_ENV=dev ~/bin/pbdev --mock --preload

Note that the above does give me a mock network, but no preloaded account. I did create one with username and credentials mocksafenetworkdeveloper which shows that the account was not preloaded. To confirm the args are being picked up I was able to access the live network with:

NODE_ENV=dev ~/bin/pbdev --live

**Comment by joshuef** [comment]
Odd. On the safe_browser/peruse branch I can login, but not see see `safe://api.playground`.

@b-zee reported the following to me on the forum: 

![](https://forum.safedev.org/uploads/default/original/1X/9f05a97f53a79e7a0438b19dd1a5a1c1f325f346.png)

Which is happening on linux with `--mock --preload` flags. (which seems to be failing to load libs)

**Comment by hunterlester** [comment]
@joshuef @bochaco I'm not able to commit a `MockVault` to the repo without it getting corrupted. I thought maybe it was platform dependent but the file is still not usable between Linux VM's.
I'm wondering if this feature should just be deprecated?

**Comment by bochaco** [comment]
@hunterlester have you compared the file before and after committing it to verify if there is effectively any difference?
Also, perhaps related to git not detecting it as binary and corrupting it anyhow? https://bluishcoder.co.nz/2007/09/06/git-binary-files-and-cherry-picking.html

**Comment by hunterlester** [comment]
@bochaco Thank you! That worked.

**Comment by bochaco** [comment]
Excellent @hunterlester !!
