### ISSUE TITLE
Reconnect works for the authenticator but not for re-opening a website from a tab

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#319]
After the network has been disconnected, triggering the "reconnect" action from the authenticator page, it seems to reconnect successfully for the authenticator as I can fetch info of authorised apps again, but I cannot load any website from a tab

**Comment by S-Coyle** [comment]
TBC whether this is definitely for milestone 0.7.0. To discuss once Gabriel is online

**Comment by bochaco** [comment]
I just changed milestone to v0.7.1 as I think we can release v0.7.0 without this fixed.

**Comment by hunterlester** [comment]
Resolved as of https://github.com/maidsafe/safe_browser/commit/7bb12daf308498252abbbecac3fce6c703a2672c and in [peruse-0.7.0-rc.3](https://github.com/maidsafe/safe_browser/releases/tag/untagged-c4d927a29108e59d34b5) release
