### ISSUE TITLE
Linux packaged peruse version crashes when using `--debug`

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#322]
Operation System and Version: Ubuntu 18
SAFE Browser Version: Peruse 0.7.0-
Network: Mock
Description: Linux packaged peruse version crashes when using `--debug` arg
Steps to reproduce: package it and try to use `--debug` mode

**Comment by hunterlester** [comment]
Unable to reproduce this issue building with master @ https://github.com/maidsafe/safe_browser/commit/f1b80cf1016d6a14b4f55b57223fab87b1100ce6.

**Comment by bochaco** [comment]
I'm not reproducing this either on Linux Debian 9 with same commit of the browser @hunterlester .

**Comment by hunterlester** [comment]
@joshuef Are you still able to crash the browser?

**Comment by shriram2301** [comment]
@joshuef  I tried reproducing this with the same commit that @bochaco and @hunterlester did. I wasn't able to reproduce it either.

**Comment by joshuef** [comment]
It's not crashing for me no, but we're not getting into full debug mode either... (with devtools windows showing for the browser).

I'll close this as it's not strictly _the_ issue then. And create a new one to track what _should_ be happening in `--debug` mode in a packaged browser.
