### ISSUE TITLE
If I log out of account in Peruse 0.7.0 I can still use the "Read Browser State from SAFE" option to retrieve the previously logged in users bookmarks & history. Can also reopen last tab.

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe_browser#324]
mock.
osx.

Reproduced on 0.6.0 as well.
Steps: login, add bookmarks & create history, kill browser, reopen browser & login again, logout, click to read browser state.

**Comment by joshuef** [comment]
Resolved via #374

**Comment by safesurfer** [comment]
QA verified
