### ISSUE TITLE
Multiple devtools warnings:

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe_browser#330]
* "Hash history cannot PUSH the same path..."
* "Each child in an array or iterator should have a unique 'key' prop..." x2

Peruse-v0.7.0-rc.2 prod
osx

![image](https://user-images.githubusercontent.com/37112040/45207501-0557d380-b280-11e8-8f5c-34f96b682735.png)

No noticeable adverse effect in my browsing as yet

**Comment by S-Coyle** [comment]
Also note that opening the Peruse-Shell Devtools shows a list of different errors:
![image](https://user-images.githubusercontent.com/37112040/45207647-68e20100-b280-11e8-91e1-bf3ef3e1cdae.png)

**Comment by hunterlester** [comment]
https://github.com/shriram2301/safe_browser/compare/issue330...hunterlester:330
