### ISSUE TITLE
Prompted to authenticate Peruse twice

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe_browser#332]
Reported by @lionel1704 who is able to reproduce this consistently.
Peruse 0.7.0-rc.2
Platform = Windows 
Builds = mock and dev

Noticed this happened to me on osx once, but unable to reproduce.

**Comment by joshuef** [comment]
I'd wager this needs to be if/else then:

https://github.com/maidsafe/safe_browser/blob/peruse/app/extensions/safe/peruseSafeApp/index.js#L87-L92
