### ISSUE TITLE
The 'Download Now' button on the get involved page (safenetwork.tech) link changed to take to the safe_browser release page

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/safe_browser#350]
Is there a link we can give it that is always just the latest stable release? That way we can update it ahead of time, and it also doesn't need to be changed in the future.

Edit: Just realised @bochaco has suggested this already in #355

**Comment by hunterlester** [comment]
Resolved by https://github.com/maidsafe/safenetwork.tech/pull/100
