### ISSUE TITLE
Enable the `Latest release` link on safe_browser repo to use as download link from all websites

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#355]
To avoid having to update all webites' download link, we should try to enable the `Latest release` link on github for the safe_browser repo:
- https://help.github.com/articles/linking-to-releases/#linking-to-the-latest-release
- https://github.community/t5/How-to-use-Git-and-GitHub/Why-last-release-is-not-marked-as-quot-latest-release-quot/td-p/1762

For a quick test, we can publish a dummy release from a fork without the "pre release check box" and see if its getting the "latest release". If it does, might make a case to apply the "pre release checkbox" only for our `rc` (release candidate) releases which the `latest release` URL will hopefully not pick.

**Comment by hunterlester** [comment]
Resolved by PR's: 
https://github.com/maidsafe/dev_website/pull/46
https://github.com/maidsafe/safenetwork.tech/pull/100

**Comment by bochaco** [comment]
ok, as mentioned above it was just about removing the `prerelease` checkbox, so the links work correctly now.

**Comment by bochaco** [comment]
Closing this as https://github.com/maidsafe/safe_browser/releases/latest is already enabled.
