### ISSUE TITLE
OSX open/close/minimise buttons, linux menu bar

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#362]
With latest changes to window framing, we're missing some traditional buttonage on OSX, and it seems that latest versions of the ubuntu/gnome combo do net get a menu.

ubuntu/gnome is now the default desktop as opposed to unity in previous versions, so I'd say we need to treat gnome as first class here (and not unity).

**Comment by theWebalyst** [comment]
Doesn't look relevant, but just in case when I start Peruse 0.7 (which lacks a menu bar for me on Ubuntu 18) I see this:

```
(pb70:5001): Gtk-WARNING **: 14:48:31.188: Theme parsing error: gtk-main.css:79:38: Failed to import: Error opening file /home/mrh/.themes/MyRadiance/gtk-3.20/apps/gnome-builder.css: No such file or directory
```

**Comment by joshuef** [comment]
It was an electron setting, @theWebalyst . This will bring the menu bar back on gome desktops, although it will appear quite large for now (as seems to be gnome's style).

We'lll tackle that in another issue 👍
