### ISSUE TITLE
Linking to other safe/clearnet sites doesn't work, v0.7.0

### ISSUE THREAD

**Issue by JPL1** [maidsafe/safe_browser#368]
Operation System and Version: OS = Win 10
SAFE Browser Version: Peruse 0.7.0
Network: <Testnet, Alpha, Mock> Alpha2
Description:  Clicking on a link to page in a subdomain or to the c;learnet just refreshes the page.

I've started re-uploading the safe://safenetworkprimer site. So far www.safenetworkprimer and chapter2.safenetworkprimer are in place. However I've noticed that when I click on a link from one to the other, the original page simply refreshes rather than bringing up the new one.

To reproduce:

Go to safe://safenetworkprimer
Click on the link "2. A short history of decentralized networks" under Contents, left hand panel.

Expected result:
chapter2.safenetworkprimer opens.

Actual result:
safe://safenetworkprimer refreshes

The same thing happens with all links, including clearnet links (eg click on one of the links at the bottom of the page under Tell me more)

EDIT: I think this is probably something to do with safe://safenetworkprimer but this issue does not occur on this site using SAFE Browser 0.1.2
EDIT: Also occurs with safe://racer.game

**Comment by bochaco** [comment]
This seems to be the exact same issue as #359. I just tried safe://safenetworkprimer with v0.7.0 and I can reproduce the problem described in #359. Also, I just tried that site with PR #365 and it seems solved.

**Comment by hunterlester** [comment]
Resolved, having tested with https://github.com/maidsafe/safe_browser/commit/9f51fc317a637716695038667076a5aa582648df
