### ISSUE TITLE
Make sure package name is correct

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#380]
We need to update naming for the repo to Safe Browser

This will need to update a couple of paths, as well as the electron process naming for OSX.

We should check that the browser loads properly, is packaged and named correctly and that auth uris etc load properly.

**Comment by bochaco** [comment]
@hunterlester @joshuef , I see there is a `window.Peruse` object exposed which contains the `version`. 
I'm wondering if as part of this issue we can change it to be exposed at `window.browser`, `window.safebrowser`, or something else, and have the version and perhaps release name, e.g. `{ version: "0.7.0", release: "Peruse" }`
