### ISSUE TITLE
Migrate from AppVeyor to Travis

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_browser#397]
https://blog.travis-ci.com/2018-10-11-windows-early-release

**Comment by bochaco** [comment]
This would be nice so we have just one CI platform

**Comment by joshuef** [comment]
Just for reference: we're currently getting free space issues 

https://travis-ci.org/joshuef/safe_browser/builds/441430405

Which is a travis issue, that they're on

**Comment by hunterlester** [comment]
I tried Windows platform out for `safe_app_nodejs` and it will gets past the worker start-up: https://travis-ci.org/hunterlester/safe_app_nodejs/jobs/440766915

**Comment by joshuef** [comment]
blocked by #455

**Comment by manavbp** [comment]
Closing this issue as we have completely migrated from AppVeyor to Travis on all three platforms/
