### ISSUE TITLE
MockVault seems to get corrupted after an app is authorised

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_browser#400]
>I just created an account on a fresh mock file (secret/pass: `letstestthesafenetwork`), then I used our web API playground tool to authorise an app, when the app tries to connect using the auth URI it received, error `-2000: Unexpected (probably a logic error): Could not connect to the SAFE Network` is returned.

ref: https://maidsafe.atlassian.net/browse/MAID-2658

**Comment by hunterlester** [comment]
Thanks to @bochaco 
Until we track down this bug, the simple work around is to perform a `webFetch` right after [`loginFromUri`](https://github.com/maidsafe/safe_examples/blob/master/safe_web_app_quick_start/src/safenetwork_code.js#L15).
It doesn't have to be a successful web fetch.
`await safeApp.webFetch('safe://example');`

**Comment by hunterlester** [comment]
Resolved by https://github.com/maidsafe/safe_client_libs/pull/683

**Comment by bochaco** [comment]
Just to make it clear, this will be solved when we upgrade safe-node-app package to v0.10.0, i.e. when issue #412 is resolved.

**Comment by safesurfer** [comment]
QA verified
