### ISSUE TITLE
Enhance the authorisation popup

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#405]
The authorisation popup shall be enhance specially to make it more clear and evident which set of permissions are being requested by the app.
We should also make sure we have two different type of message in the pop-up for the case that the app was already authorised before and it's just being re-authorised by the authenticator, since in this case the permissions sent in the new request are ignored and the authorisation will allow the app only the permissions requested in the irst authorisation request, this usually can create a confusion.
More info here: https://forum.safedev.org/t/container-access-any-recent-dom-api-changes/1314/5

**Comment by safesurfer** [comment]
QA verified
