### ISSUE TITLE
Auth popup is not shown after denying/ignoring an shared MD auth request

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#407]
If I deny or ignore (by clicking the `x` button in the auth popup) an authorisation request for sharing a MutableData (https://docs.maidsafe.net/safe_app_nodejs/#authinterfacegensharemdatauri), then subsequent authorisation requests (even auth reqs for connecting) from any webapp are not triggering the auth popup in the authenticator.

Also when denying/ignoring the request, the call to `window.safe.authorise` is not being rejected as I would expect (it's not being resolved either).

It sounds a similar issue to this one: https://github.com/maidsafe/safe_browser/issues/387

**Comment by S-Coyle** [comment]
@shriram2301 Is this down to a generic bug with SCL? (not fixed in 0.9.0)

**Comment by safesurfer** [comment]
verified and tested using web-api-playground.
