### ISSUE TITLE
Fetch app triggering 'unauthorised' response

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#411]
As it stands, @nbaksalyar is seeing 'Unauthorised, cannot connect to network' on both OSX and Ubuntu 18, for dev mode and prod (packed/unpacked).

@joshuef has reproduced in OSX `prod-dev` mode, and can see:

```
[13:00:55.600] Authenticator.js decoding request safe-auth:bAAAAAAELWIZN6AQAAAABSAAAAAAAAAAANZSXILTNMFUWI43BMZSS443BMZSS2YTSN53XGZLSAA
renderer.js:34 [13:00:55.660] Wrapping Address bar buttons LHS
renderer.js:34 [13:00:56.108] Authing from a store-passed response. 1541678456107 Unauthorised
```

Which is the fetch applications unauthed client returning an `unauthorised` error for some reason...

TODO:
- Check ubuntu / windows for similar issue / confirm that this is happening across all.
- Fix!

**Comment by joshuef** [comment]
This was related to an error in the safe client libs deploy procedure. Not browser related/

**Comment by safesurfer** [comment]
verified
