### ISSUE TITLE
Add toggle for experimental functionality in the browser.

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#415]
With the new version of safe-node-app package (v0.10.0), the experimental APIs will be hidden behind a flag which can be set either from the command line or as part of the initialisation of a safeApp instance. Since we don't want user to have to run the browser from the command line to be able to enable them, it's proposed to have a UI switch/toggle which allow users to enable/disable the experimental APIs. The WebID drop-down feature on the browser is an example of this, so the browser would disable it until the experimental APIs are enabled from the switch/toggle.

**Comment by safesurfer** [comment]
QA Verified and turning on the toggle will show the experimental feature (WebID dropdown)
