### ISSUE TITLE
History: Changing historyIndex triggers `updateTab` on load (which increases historyIndex erroneously)

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#418]
When navigating backwards/forwards a new history entry is added instead of reducing the history index by one, to show that its relative place in the history

**Comment by joshuef** [comment]
So, actually the `updateTab` triggerd on load when loading the new history updates the tab (as it should).

But we don't want this to be added to history, nor change the index...

**Comment by joshuef** [comment]
To check, try adding new urls, then progress backwards a few times / forwards a few times.

Things should go in order now (where history was being broken previous)

**Comment by safesurfer** [comment]
QA verified
