### ISSUE TITLE
Sort out and clean up how styles are loaded

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_browser#421]
For example, we need to ability to import `antd` or `nessie` styles in this file: https://github.com/maidsafe/safe_browser/blob/master/app/extensions/safe/components/authRequest.js

Currently when importing a CSS file, it's not being picked up by `css-loader` in webpack and so is treated as a JS module.

Perhaps nessie styles, or future `antd` styles could be loaded globally using webpack instead of  being loaded [here].

**Comment by joshuef** [comment]
This is sorted in the ExperimentalToggle branch.

**Comment by joshuef** [comment]
@safesurfer this was a refactor to enable `antd` (ant design).

The successful integration can be verified by the presence of new ant design items such as buttons:

https://www.dropbox.com/s/ebm9hlta7pqqqhb/Screenshot%202018-12-03%2018.37.13.jpg?dl=0

**Comment by safesurfer** [comment]
QA verified
