### ISSUE TITLE
Update safe_app to avoid webview crash if the experimental APIs are disabled

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#430]
If the experimental APIs is disabled in the browser, trying to access the `safeApp.web` experimental APIs from the devTools console, the devtools get disconnected form the page and a blank page is rendered in the current tab. I tried to reproduce it from the web API playground tool but I wasn't able to, it seems to be only when I instantiate a safeApp from the devTools console with:
```
window.safe.initialiseApp({
    id: 'net.maidsafe.test.webapp.id',
    name: 'WebApp Test',
    vendor: 'MaidSafe Ltd.'
  }, (newState) => {
    console.log("Network state changed to: ", newState);
  }).then(app => safeapp = app)
```
and then 
```
safeapp.web.
```

![screenshot from 2018-11-27 22-43-33](https://user-images.githubusercontent.com/442821/49123157-57fcc680-f296-11e8-98e6-39f218a28e49.png)

**Comment by joshuef** [comment]
This will be solved via updating `safe_app` version with fixes from: https://github.com/maidsafe/safe_app_nodejs/pull/320

**Comment by safesurfer** [comment]
QA verified
