### ISSUE TITLE
Reloading a page due to enabling the experimental APIs causes a `Setup Incomplete` error

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#433]
When reloading a page due to switching the toggle for experimental APIs, the page can get a `Setup Incomplete. Connection not available yet.` if the user doesn't authorise the browser app quickly enough, it seems the page being reloaded tries to make use of the new safeApp instance before it's being fully setup.

**Comment by joshuef** [comment]
Fixed on the #420 branch

**Comment by safesurfer** [comment]
QA verified
