### ISSUE TITLE
Going back to `about:blank` the page is not refreshed/cleared

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#434]
After fully loading a webpage/webapp in a tab, and click the button to go backwards, the address bar displays `about:blank` as expected but the webpage is not refreshed/cleared.

**Comment by calumcraig** [comment]
Tested this and behaviour is now:
1. Open new tab in browser - so address is `about:blank`
2. Paste a SAFE link into this tab?
3. Wait til page is loaded
4. Click back on browser
5. Page returns blank and address reads `about:blank`

Confirmed with dev team that this expected.
Moving to done.
