### ISSUE TITLE
Enhance CI config to pull resources from release_config

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_browser#440]
Specifically to pull `log.toml` and `crust.config`.

**Comment by joshuef** [comment]
is this still needed with latest master?

**Comment by hunterlester** [comment]
Still needed. Relying on resources bundled with this repo.

**Comment by joshuef** [comment]
closing as non relevant now

**Comment by safesurfer** [comment]
Pushing it to Done, since it works fine, and not seeing any issues.
