### ISSUE TITLE
Getting connection failed error when I try to open browser (prod) on Windows

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#441]
I tried running browser (prod version) for windows which is downloaded from RC1 release, getting this error `Check your current IP address matches your registered address at invite.maidsafe.net`, though I've updated my IP.

Note: It works on MacOS (confirmed by @S-Coyle) and Linux.

**Comment by joshuef** [comment]
Just to confirm. This was when running `prod-dev`? correct @safesurfer ?

And you had run `yarn put-live-net-files-for-windows`?

**Comment by safesurfer** [comment]
Yes @joshuef , it happened when running `prod-dev` as well as the rc1 production package. @hunterlester has figured it out and told it was because of the name mismatch between the `crust.config` and executable.
