### ISSUE TITLE
When running in dev mode it seems to not receive auth requests (linux)

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#443]
When running the browser with `yarn mock-dev`, and then trying to authorise the WHM, the request doesn't reach the browser, it seems to be that the browser is not registering correctly in linux in dev mode, the following error is thrown on the WHM shell console:
```
Error launching app
Unable to find Electron app at /home/bochaco/work/bochaco-safe_browser/app/main.js

Cannot find module '/home/bochaco/work/bochaco-safe_browser/app/main.js'
```
I also tried running the packaged browser and I was able to authorise the WHM on linux, so it's probably just the browser when launched in dev mode.

**Comment by bochaco** [comment]
This is simply solved by running `yarn build` before `yarn mock-dev`, that generates the script that is needed for receiving the authorisation requests thru system URI. We can discuss if we want this to be added as a `postinstall` step.

**Comment by safesurfer** [comment]
QA verified by running WHM with `NODE_ENV=test`
