### ISSUE TITLE
Crust config needs to match executable

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_browser#444]
On Windows, should be `SAFE Browser.crust.config` instead of  `safe-browser.crust.config`.

**Comment by joshuef** [comment]
@hunterlester FYI, we have [post-pack](https://github.com/maidsafe/safe_browser/blob/master/post-pack.js) to handle this stuff. Looks like it just needs to be updated after the package rename for win 👍

**Comment by safesurfer** [comment]
QA Verified
