### ISSUE TITLE
Switching tabs opens new tabs in clearnet browser, when we try to open `http/s` protocol

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#450]
There is an issue with switching tabs/opening new tab/closing newly opened tab, when we try to access `http/s` protocol in safe_browser. 
For ex: If I try to open `https://www.google.com` in safe_browser it redirects the url to clearnet browser and I'm getting `Detected http/s protocol` message on the page. 
If I open a new tab next to the page which contains the above said message or switch between tabs or closing the newly opened tab, opens new tab with that https url in the clearnet browser.

Note: Tested on Windows and Ubuntu.

**Comment by safesurfer** [comment]
QA verified

**Comment by safesurfer** [comment]
One more issue, getting blank white page if I try to access any `http/s` links from the authenticator page with just `Menu bar`

STR:
1. open the browser and replace the auth page's address bar with any `http/s` link like `https://www.google.com`
2. it opens the link in clearnet browser, but it leaves the safe browser with blank white page with just `Menu bar`

**Comment by joshuef** [comment]
The latter makes sense and #518 is looking good 👍

**Comment by safesurfer** [comment]
QA verified that #518 resolves https://github.com/maidsafe/safe_browser/issues/450#issuecomment-452654571 and for the issue https://github.com/maidsafe/safe_browser/issues/450#issuecomment-452634824, hunter has opened a new issue #517 .
