### ISSUE TITLE
Shared MD authorisation request not rejected if MD doesn't exist

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#452]
When sending an authorisation request for shared MD, there is no response if the targeted MD doesn't exist on the network.

Also, when clicking the `x` button in an authorisation popup a "rejected" auth response is sent back to the app instead of just ignoring it and not send any response at all:
![image](https://user-images.githubusercontent.com/442821/50484102-95578f80-09cd-11e9-82b2-c1e3d62c0b6e.png)

**Comment by hunterlester** [comment]
Snippet to quickly test in API playground:

```
      const appInfo = {
        id: 'net.maidsafe.api_playground.webclient.9',
        name: 'SAFE web API playground',
        vendor: 'MaidSafe Ltd.',
        scope: null
      };

      try {
        let app = await safe.initialiseApp(appInfo);
        const authReqUri = await app.auth.genAuthUri();
        const authUri = await safe.authorise(authReqUri);
        app = await app.auth.loginFromUri(authUri);
        const hashedString = await app.crypto.sha3Hash('1010101010101');
        const permissions = [{
          typeTag: 15001,
          name: hashedString,
          perms: ['Insert']
        }];
        const shareMDataReqUri = await app.auth.genShareMDataUri(permissions);
        await safe.authorise(shareMDataReqUri);
      } catch (err) {
        return err;
      }
```

**Comment by hunterlester** [comment]
Setting this aside to think about how best to resolve a few contributing issues that comprise this issue.
WIP: https://github.com/hunterlester/safe_browser/tree/452

**Comment by hunterlester** [comment]
Setting `blocked` on this issue until I confirm with SCL where the root lies.

Issue can be observed when `auth_decode_ipc_msg` is called on a `ShareMDataReq`, composed of an `XorName` which doesn't exist on the network.
Expecting to receive `CoreError(No such data - CoreError::RoutingClientError -> NoSuchData)`, assigned to the `err` variable, which I successfully log here: https://github.com/maidsafe/safe_client_libs/blob/master/safe_authenticator/src/ffi/ipc.rs#L179
Expecting this value to be passed as the 3rd argument of `o_err` callback.
However, I observe a `null` value, received by browser's `safe_authenticator` implementation.
Looking at the behavior of the `call_result_cb!` macro, in this context it passes a default `ptr::null()` as the third callback argument: https://github.com/maidsafe/ffi_utils/blob/master/src/macros.rs#L70
So does that mean a `ptr::null()` is expected? Even if so, I'd then expect to log a null pointer and not simply a `null` value.
The second argument of the callback call is an `FffiResult`, which I observe in the browser's authenticator to log what looks like a pointer whose referenced values have been freed from memory.
When I dereference `<Buffer@0x000001E8E1F07A30 99 ff ff ff 20 02 00 00 40 12 33 3b 20 02 00 00>`, it's an unreadable value.

**Comment by m-cat** [comment]
Hey @hunterlester, I've investigated this and so far found nothing out of the ordinary that would be causing any issues.

> So does that mean a ptr::null() is expected? Even if so, I'd then expect to log a null pointer and not simply a null value.

It's valid, and it's the same thing I see in our Rust-side `share_mdata` tests where an error is expected.

> The second argument of the callback call is an FffiResult, which I observe in the browser's authenticator to log what looks like a pointer whose referenced values have been freed from memory.

This is the only part that worries me. You should be able to reference the `FfiResult` here to get the error information -- it's what we do in our Rust tests. Can you confirm that this is not an issue of garbage collection in the browser or something along those lines?

I don't see anything weird on the Rust side and we handle this error the same way as we do everywhere else. It's possible that our current error handling is incorrect and you've discovered a case where the `FfiResult` value is dropped when it shouldn't be.

**Comment by safesurfer** [comment]
QA verified, ref: https://github.com/maidsafe/safe_browser/pull/554#issuecomment-470449730
