### ISSUE TITLE
Automatically reject authorisation request which mockbit doesn't match

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#454]
For the scenarios when the browser is running for mock network, and an application sends an authorisation request which is for live network (or the other way around), the authenticator should be rejecting the authorisation automatically and sending such a response to the application. Currently the application doesn't receive any type of response.

**Comment by bochaco** [comment]
@hunterlester , I'm not sure if the implemetation you are working on for this issue would also cover the case when the request sent is an old base64 encoded auth URI? would in this case also be ignored by the authenticator and we can also send a propoer response to the app rejecting the auth?

**Comment by safesurfer** [comment]
QA verified, ref: https://github.com/maidsafe/safe_browser/pull/554#issuecomment-470449730
