### ISSUE TITLE
"About SAFE Browser" version details need updated automatically with standard-version bump

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe_browser#460]
![image](https://user-images.githubusercontent.com/37112040/49792132-dabb6200-fd29-11e8-86be-e1197cbcdee1.png)

**Comment by joshuef** [comment]
Actually, this is a non issue as it's pulled from the package.json version, which we're already updating on version bump. 

We just haven't bumped the version in this branch yet.

This is resolved via #456
