### ISSUE TITLE
SAFE browser 1.0.0-rc2 menu items not functioning on Linux

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#462]
**Steps to reproduce:**
1. Launch SAFE browser 1..0.0-rc2 on a Linux OS.
2. Try to select menu items under "SAFE Browser" menu.

**Expected:**
Menu items (About, Hide / show, quit) all function.

**Actual:**
Only quit functions - other menu items are unresponsive.

**Environments:**
Discovered on Linux Mint 19 Cinnamon.
Replicated on Ubuntu 18.04 VM

![image](https://user-images.githubusercontent.com/44327924/49798966-93d66800-fd3b-11e8-9ef3-bb967746fe1f.png)

**Comment by hunterlester** [comment]
Same  behavior on Windows.

**Comment by hunterlester** [comment]
This settings column is MacOS-specific: https://electronjs.org/docs/api/menu#notes-on-macos-application-menu

**Comment by calumcraig** [comment]
The SAFE Browser has now been removed from Linux (and Windows):
![image](https://user-images.githubusercontent.com/44327924/50898604-98a83d80-1407-11e9-8e43-f0d2f66e13bb.png)
The quit function seen previously is now provided by "Close window" option in the file menu.
