### ISSUE TITLE
SAFE browser 1.0.0-rc2 - focus not on text field when browser is launched

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#465]
**Steps to reproduce:**

1. Launch SAFE browser 1.0.0-rc2
2. Attempt to enter secret answer

**Expected:**
User can immediately type into the text field for secret answer - there is a flashing cursor in the field.

**Actual:**
Focus is not on text field and user needs to manually click into the field before they can enter text.

![image](https://user-images.githubusercontent.com/44327924/49807888-1d456480-fd53-11e8-975c-0cdca954ddfa.png)

**Environments:**
Found in Linux Mint 19 Cinnamon.
Replicated in Ubuntu 18.04 VM
Expected behaviour IS seen on Mac OSX.

**Comment by hunterlester** [comment]
Same on Windows. The text field is not focused on login text field.

**Comment by calumcraig** [comment]
Retested defect after the above changes and now working as expected. When the browser is launched, focus is on the Secret answer field and user is able to immediately type into the field:
![image](https://user-images.githubusercontent.com/44327924/50896483-0735cd00-1401-11e9-8b9c-bb797a62a1eb.png)

**Comment by calumcraig** [comment]
Reopening this issue as need to confirm behaviour. Despite the above, some discrepancies have been observed by myself and @safesurfer.

**Comment by hunterlester** [comment]
I should have commented here in addition to associated PR. I'll favor commenting in issues in the future.
PR #398 changes the expected behavior of the text field to only focus upon user `TAB`ing or selecting input with mouse.

Tested on OSX, Linux, and Windows. Upon first executing browser, "Account Secret" input field focuses upon once hitting `TAB`.

**Comment by calumcraig** [comment]
Confirmed that current behaviour is that tab / mouse click is required to focus into text box. As noted by @hunterlester this is expected.

OK to close issue.
