### ISSUE TITLE
Seeing a white blank screen on the browser, when I try to open a safe link, by clicking it.

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#471]
when I try to open a safe link for ex: `safe://webidmgr.exampleapps1` by clicking it, which opens the browser (live) and it is just showing a white screen with the browser menu.

![screenshot from 2018-12-13 19-01-20](https://user-images.githubusercontent.com/27578024/49944744-2d0aa780-ff11-11e8-9dac-e7c7bbd20555.png)

This happens only when the browser is not running in the background. If it is running and logged in, it works fine.

STR:
1. close the browser if it is running
2. click the safe link, it will try to open safe-browser. (note: the live browser would have opened once before trying this)
3. it will show you blank screen on the browser.

Tested and confirmed on Windows, Ubuntu and Mac OS.

**Comment by joshuef** [comment]
@safesurfer can you please get the logs from the browser at the time of the crash (`yarn log` from inside the repo should get them), then you can trigger the error

**Comment by joshuef** [comment]
just confirmed this behavior from 0.7.0 too actually.

**Comment by joshuef** [comment]
sorted ittt
