### ISSUE TITLE
Can't unhide Account secret / password before typing

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#473]
When logging into SAFE browser there are "eye" icons to display the text for account secret / password:

![image](https://user-images.githubusercontent.com/44327924/49953181-71884a00-fef5-11e8-8157-231e576ecc74.png)

However, the toggle between hidden / unhidden text only works when the text fields are populated so a user cannot click them _then_ start typing to be able to see their text - they must started typing (hidden) then toggle to unhidden.

Would it be more user friendly to have this so that the user can select the toggle _before_ entering any text?

**Comment by manavbp** [comment]
Closing this issue as the authenticator is not a part of the safe browser with the new Pweb browser changes.
