### ISSUE TITLE
WebID Profile Manager - no character limit on Nickname and Name fields.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#475]
**Steps to reproduce:**
1. Launch SAFE browser and sign in.
2. Navigate to Web ID Profile Manager:
safe://webidmgr.exampleapps1/#/list
3. Click create new WebID Profile.
4. Enter text into Nickname and Name fields.

**Expected:**
Limit of no. of characters a user can enter.

**Actual:**
There appears to be no limit on no. of characters a user can enter into these fields. Entering long strings of text then causes UI issues when user returns to the list of WebIDs:
![image](https://user-images.githubusercontent.com/44327924/50002094-e52e6380-ff96-11e8-848a-52aea30966d1.png)

**Comment by bochaco** [comment]
Thanks @calumcraig , please note that the WebID Mgr app has its own repo, please raise any other issues related to WebID Mgr app there: https://github.com/maidsafe/safe-web-id-manager-js/issues
I can move this one over later on.

**Comment by calumcraig** [comment]
Thanks @bochaco , I didn't realise about the other repo - duly noted.

**Comment by bochaco** [comment]
No worries @calumcraig , closing this one now as we can now track it with https://github.com/maidsafe/safe-web-id-manager-js/issues/14
