### ISSUE TITLE
Not able to access the tabs through `Select Next/Previous Tab` or Pressing `Ctrl+Tab/Ctrl+Shift+Tab` if it is opened by `clicking User icon / clicking vertical ellipsis icon / clicking a safe link from outside` 

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#482]
STR:
1. Open Browser and switch on `Toggle Experiments`
2. i) Click the User Icon next to Refresh button and choose `Launch WebID Manager` which will open webID manager in a new tab. OR
ii) Click the vertical ellipsis icon next to favourite icon and choose `bookmarks/history` which will open bookmark page/ history page in new tab. (switching on `Toggle Experiments` not needed) OR
iii) Click any safe link from outside which will open the page (switching on `Toggle Experiments` not needed) 
3. Open some other tabs
4. Try to switch between tabs using `Select Next/Previous Tabs` or pressing `Ctrl+Tab/Ctrl+Shift+Tab`

Expected:
Able to access all the tabs one by one.

Actual:
It switches between all the tabs, but it skips
i) the WebID Manager tab which is opened by clicking User icon and Launching it from there
ii) bookmarks/history tabs which are opened by selecting it from `show more` menu (vertical ellipsis)
ii) any safe page opened from outside by clicking a link.

But it works well if you manually input the URL, or if it is opened from Menu bar

Platforms:
Windows 10 and Ubuntu 18.04 VM

**Comment by safesurfer** [comment]
Closing Tabs (Ctrl + W) is also not working as expected with this same scenario. It only closes all the tabs except the tabs opened using the steps provided above.

**Comment by calumcraig** [comment]
I'm experiencing the same issue moving between tabs on Linux Mint 19 Cinnamon.

Additionally, I found close tab closed the whole browser window (I had previously opened 3 / 4 tabs by clicking on links). When I then selected close tab from the file menu the whole browser window shut.

**Comment by safesurfer** [comment]
QA Verified
