### ISSUE TITLE
Add more unit tests for the address bar input component

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#487]

**Comment by shriram2301** [comment]
[-] check if props can be set up
[-] mount child components and check if following one of following components is present :
				[-] ButtonsLHS
				[-] ButtonsRHS
				[-] Input

**Comment by shriram2301** [comment]
@joshuef I'm working on these ones listed here and breaking them up further, I'll update each break up as and when I get one here. Please do add if any more extra need to be added or we can elaborate these further.

**Comment by shriram2301** [comment]
@joshuef  ah by `mount I meant mount the component and check life cycle components`,  I mean test if `componentWillReceiveProps`  does what it's supposed to do if I run something like `setProps()` . In hindsight .I am meaning  the same thing for `check if props set up can be used` that is repeating the same point.

**Comment by shriram2301** [comment]
tests to be done:
-[ ] onBlur 
-[ ] onKeyPress  
-[ ] onFocus
-[ ] onChange
-[ ] componentWillReceiveProps
	- set state if nextProps address is updated
	- test if select() is called

**Comment by shriram2301** [comment]
- [ ]check on keyPress if updateActiveTab is called
- [ ] check on handle Blur if onBlur() is called
- [ ]check on keyPress if updateActiveTab() is called
- [ ] check on handleFocus if onFocus() is called
- [ ] check on handleFocus if select() is called
- [ ] check on handleClick if select() is called
- [ ] check on handleClick if select() is not called
- [ ] check on handleChange if select() is called
- [ ] check if componentWillReceiveProps is called
- [ ] check if on componentWillReceiveProps state can be set
- [ ] check if on componentWillReceiveProps ,select() is called

**Comment by shriram2301** [comment]
@joshuef  there is no `onClick`  or event that calls `handleClick` in `Input.jsx` . So the test cases for an event `click` can't be tested unless we actually have it being called. So what do I do? Do I add an `onClick` or do I remove the `handleClick` as a refactor or leave it as is ? I'm assuming the `handleClick` was there for a reason.

**Comment by joshuef** [comment]
What is `handleClick` doing then? Maybe it's nothing?

And so... Do we need `onClick` test then?

**Comment by shriram2301** [comment]
It's doing nothing at the moment. So we don't need a test for it. I'll remove `onClick` from the tests.

**Comment by calumcraig** [comment]
Going to move this to done as there are no additional steps / tasks required of QA. We will continue to monitor CI as referenced in https://github.com/maidsafe/safe_browser/pull/561.
