### ISSUE TITLE
Antd tab close button too BIG

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#492]
Looking at the two buttons for closing / opening tabs, the close button seems _sooooo big_. 

Like, too big.

https://www.dropbox.com/s/m07e0lfzygjsocd/Screenshot%202018-12-20%2009.43.28.jpg?dl=0

Comparing that to chrome (https://www.dropbox.com/s/hy2jz6deh447v1j/Screenshot%202018-12-20%2009.46.40.jpg?dl=0), you can see that the close button is just a bit smaller. 

@shriram2301 I think we should remove the 'button' aspect of this 'close' button, and use only the icon, and then make that icon, _a bit_ smaller.

Note, the icon should still have a `pointer` on hover, and ideally some `:hover` css state to reflect this interact-ablity (as well as the click event/functionality).

**Comment by joshuef** [comment]
Just to note, this is currently tied to #669

**Comment by safesurfer** [comment]
QA verified
