### ISSUE TITLE
Can't use keyboard arrow keys to navigate between browser menus

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#494]
When browser menus are being accessed:
![image](https://user-images.githubusercontent.com/44327924/50290323-3345da00-0463-11e9-8e98-a1e9db91d62d.png)
The left and right arrow keys on the keyboard don't move between the different menus. This is the case with eg Firefox or Office apps.

**Comment by hunterlester** [comment]
Issue addressed in this PR: https://github.com/electron/electron/pull/15302
I don't see the fix in the CHANGELOG for [electron v4.0](https://github.com/electron/electron/releases/tag/v4.0.0).
This issue is dependent on us upgrading electron in https://github.com/maidsafe/safe_browser/issues/410

**Comment by S-Coyle** [comment]
Closing legacy issue - appears to be resolved now
