### ISSUE TITLE
Ensure that duplicate crust.config doesn't exist in Windows package

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_browser#495]
If packaging on Windows, [this script](https://github.com/maidsafe/safe_browser/blob/master/post-pack.js#L55) copies `crust.config` into root release directory as case-sensitive file name. `safe-browser.crust.config` will have already been copied into that same directory.

Extra `crust.config` either needs to be deleted or even better would probably be to just [renameSync](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_renamesync_oldpath_newpath).

**Comment by safesurfer** [comment]
QA Verified. Only one `crust.config` file exists in the package now.
