### ISSUE TITLE
There are several issues in the WebID swticher that need to be enhanced/fixed

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#496]
There are several issues in the WebID swticher/dropdown that need to be enhanced/fixed:

When the user is logged in, the item `Authorise to display your WebIds` is a link which even logs an error when clicked (`Uncaught TypeError: n is not a function`). That item should be just a label and the text should be improved as it's not clear what it means.

When the connecton to the network is slow, this brings some confusion to the user. The WebIDs are not displayed immediately when opening the dropdown, the `Authorise to display your WebIDs` link is shown for a few secs, then for another secs `No WebIds found` and `Updating WebIDs` items are shown, then after another few secs the webids are displayed, and this may even fail suposely due to some connection problems. We need to enhance this to have some visual indication of what's happenign in the back, perhaps a "loading" message/icon

All these issues were taken from the discussion taking place in the forum starting in this post: https://safenetforum.org/t/safe-browser-v0-11-0-release/26792/56

**Comment by shriram2301** [comment]
@joshuef @hunterlester what would be a good replacement for `Authorise to display your WebIDs`, I was thinking like something like `Login in to use your WebIds` or `Login into Authenticator to use WebIds` ? Please do give your suggestions on what sounds right semantically.

**Comment by joshuef** [comment]
`Login in to see your WebIds` sounds okay to me.

**Comment by calumcraig** [comment]
Is this related to this issue reported on the forum?
https://safenetforum.org/t/webids-not-showing-in-browser/27499

**Comment by bochaco** [comment]
I think so @calumcraig , if I understand correctly what's being reported there.

I also think I found a pattern for this issue, e.g I seem to be able to reproduce it always like this:
1. launch the browser for prod
2. log in with the authenticator
3. enable experimental apps
4. try to get the list of WebIDs form the dropdown

If I otherwise skip step 2 and log in the authenticator only after step 3, then step 4 seems to work fine, well...with its current UX limitations ofc, which we should enhance, but I get the list of WebIDs.

**Comment by calumcraig** [comment]
Hmm, I'm getting the issue in both situations - whether I log in before toggling experiments or toggling then logging in...
https://docs.google.com/document/d/1xraXXC0jT_Q2qENemcgknna1uk058WMFo7-GoceVjZ4/edit
This is prod browser I have built today.

**Comment by bochaco** [comment]
ah, ok, I was trying that with v0.11.1

**Comment by calumcraig** [comment]
The forum guy who raised it said he was on that version too.

**Comment by bochaco** [comment]
Yes, and just to clarify, this was reported when we released v0.11.0, as you can see in the description, so it's not a change that broke it but an earlier known issue. I belive that after the very next release where we tackle some higher priority bugs we can put this in the top of the list for next release, assuming we can have the UX/UI fully defined for it.

**Comment by manavbp** [comment]
Closing this issue as at the moment, there are no API's for creating/fetching webIds in the pweb browser.
