### ISSUE TITLE
OSX browser package has around 4 crust config files with various names in multiple locations

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#497]
The following is extracted from a discussion in our forum: https://forum.safedev.org/t/trying-to-build-a-global-network/2266/19:
"SAFE Browser release packages needs better resource bundling. Currently browser package has around 4 crust config files with various names in multiple locations thereby needing other means to identify the valid config file. Should really be pruning dev config files/… before release packaging."

I just checked v0.11.0 linux package and I can see only two, still, the one at `resources` folder shoouldn't be needed in the package
```shell
$ find . -type f -iname "*crust.config"
./safe-browser-v0.11.0-linux-x64/safe-browser.crust.config
./safe-browser-v0.11.0-linux-x64/resources/SAFE Browser.crust.config
```

**Comment by Viv-Rajkumar** [comment]
In OSX, the latest release non-dev has a few more:

```
./SAFE Browser.app/Contents/safe-browser.crust.config
./SAFE Browser.app/Contents/Resources/SAFE Browser.crust.config
./SAFE Browser.app/Contents/SAFE Browser.crust.config
./SAFE Browser.app/Contents/Frameworks/SAFE Browser Helper.app/Contents/MacOS/SAFE Browser Helper.routing.config
./SAFE Browser.app/Contents/Frameworks/SAFE Browser Helper.app/Contents/MacOS/SAFE Browser Helper.crust.config
```

**Comment by joshuef** [comment]
This is sorted on master.

QA: in a folder with the release on macOs run `find . -name "*crust*"`

**Comment by safesurfer** [comment]
Tested by building package on OSX (VM), the release folder contains only one `crust.config` file at this location `./SAFE Browser.app/Contents/Frameworks/SAFE Browser Helper.app/Contents/MacOS/SAFE Browser Helper.crust.config`.

**Comment by safesurfer** [comment]
QA verified
