### ISSUE TITLE
Some warnings are seen in the browser dev tools console

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_browser#498]
After logging in the authenticator, some 
react warnings are shown in the dev tools console which shall be removed

![screenshot from 2018-12-26 17-55-51](https://user-images.githubusercontent.com/442821/50457068-9dfd8680-0937-11e9-9b41-333762546a5a.png)

**Comment by safesurfer** [comment]
I don't see any missing key props error from React when I log in to the authenticator. But while opening Browser I see the following error similar to this on Windows. Is this OK? @hunterlester
![image](https://user-images.githubusercontent.com/27578024/56880332-e5c52380-6a79-11e9-85ab-832c54619a2f.png)
