### ISSUE TITLE
Dragging title URL crashes browser on Ubuntu

### ISSUE THREAD

**Issue by traktion** [maidsafe/safe_browser#501]
I accidentally dragged/dropped the text from the URL bar and it locked the browser. I had to restart the browser to continue.

To repeat:

- Double click on URL in bar
- Drag text then let go of mouse button
- Browser hangs and restart is required to resolve.

**Comment by traktion** [comment]
My platform is Ubuntu 18.10 with a relatively default setup.

**Comment by calumcraig** [comment]
Thanks for confirming - I'm running Mint 19 which is essentially Ubuntu 18.04.

**Comment by theWebalyst** [comment]
I still have this in v0.11.2 x64 dev build (Ubuntu 18.10 / Gnome)

**Comment by calumcraig** [comment]
Hi Mark, yes, you will still have this issue - it hasn't been completed yet - it's still being worked on. So, this week's new release won't have resolved it I'm afraid.

**Comment by joshuef** [comment]
Sorted in #700

**Comment by theWebalyst** [comment]
This is still happening to me:

Ubuntu 18.10
safe-browser-v0.13.0-linux-x64-dev

**Comment by safesurfer** [comment]
This issue has been resolved with the latest. But I've tried it with `prod-dev` and `mock-dev`. there is another issue with packaging browser, #750 , which is in progress. So I'm not able to confirm it with Packaged version of browser.

**Comment by safesurfer** [comment]
QA verified, with the packaged version of browser on Ubuntu.
