### ISSUE TITLE
IP error mismatch message doesn't refresh after IP address has been updated.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#514]

**Comment by calumcraig** [comment]
**Steps to reproduce:**
1. Launch Safe Browser from a different IP address than has previously been registered to that account.
2. Browser warns user that IP address doesn't match the registered one:
![image](https://user-images.githubusercontent.com/44327924/50895106-069b3780-13fd-11e9-9ae3-6f139afd79fc.png)
3. Visit invite.maidsafe.net (in normal browser, eg Chrome) and update IP address associated with the account.
4. Return to Safe Browser, refresh page.
5. Log into Safe Network.

**Expected:**
IP mismatch error message to clear from the screen once IP address has been updated.

**Actual:**
IP mismatch error message remains displayed and even persists after user has successfully logged on to the Safe network:
![image](https://user-images.githubusercontent.com/44327924/50895247-73aecd00-13fd-11e9-88a2-5b0dcb04bc7a.png)

**Comment by calumcraig** [comment]
A similar issue can be observed for a "not authorised" error message:

1. Launch SAFE browser.
2. Enable experiments, click "Launch Web ID Manager":
![image](https://user-images.githubusercontent.com/44327924/51549656-b5f6f600-1e62-11e9-9237-4d0d39b5b8dd.png)
3. Return to Authenticator tab and log into SAFE network.

Expected:
"Unable to to connect to the network, Unauthorised" message to clear once user has logged on.
Actual:
"Unable to to connect to the network, Unauthorised" message persists:
![image](https://user-images.githubusercontent.com/44327924/51549863-11c17f00-1e63-11e9-85f0-f752ede19962.png)

**Comment by joshuef** [comment]
should have some reconnect capabilities as with #457

**Comment by manavbp** [comment]
Closing issue as its irrelevant with the new Pweb browser changes. As the new browser set up connects to the shared/local vault rather than the alpha two network.
