### ISSUE TITLE
Save / read browser state from SAFE network options missing from File menu.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#515]
Under File menu there were previously the options:

- Save browser state to SAFE network
- Read browser state from SAFE network

These are no longer seen in the menu:
![image](https://user-images.githubusercontent.com/44327924/50897692-c5a72100-1404-11e9-965d-f2f9789f4b9b.png)

**Comment by hunterlester** [comment]
Regression fixed. `File` menu became `&File` when I added the ability to access menu items with `ALT`.
