### ISSUE TITLE
History tab/Bookmark tab reloading issue

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#520]
Tabs are reloading when you switch to it, after tried reloading either `Bookmark page` or `History` page.

STR:
1. Open Bookmark tab or History tab
2. Click Refresh button, it doesn't seem reloading the page.
3. Try to switch auth page or any other tabs except those two tabs ^^

Expected:
History Tab/Bookmark tab should be reloaded when we click Refresh button.

Actual:
It reloads the tab which you are switching to.

**Comment by joshuef** [comment]
needs updating with latest master / conflicts resolving, FYI @hunterlester
