### ISSUE TITLE
"Open new tab" right click option for link doesn't work

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#524]
**Steps to reproduce:**
1. Launch SAFE browser and navigate to safe network page which contains links, either SAFE net or clearnet. eg:
safe://safenetworkprimer
2. Right click on a SAFE or clearnet link and select "Open link in new tab".

**Expected:**
- SAFE - link will open in new SAFE browser tab.
- Clearnet - link will open in the default clearnet browser.
If user clicks on a link using CTRL + click, this does indeed happen.

**Actual:**
Nothing happens.

**Comment by calumcraig** [comment]
Tested on latest master and is now working as expected - right click "open in new tab" now opens a new SAFE browser tab for SAFE links and a new clearnet browser tab for clearnet links.

Tested on Linux Mint 19 Cinnamon - will also confirm on Mac and Windows VMs.

**Comment by calumcraig** [comment]
Confirmed working on Mac OS High Sierra.

**Comment by safesurfer** [comment]
Confirmed working on Windows too.
