### ISSUE TITLE
`Toggle Full Screen` is not toggling back to normal from full screen

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#535]
`Toggle Full Screen` is not toggling back to normal from full screen when you press F11 for the second time.

STR:
1. open SAFE Browser v0.11.1-RC2 and press F11 or click `Toggle Fullscreen` from `View` menu, now browser window will be on full screen
2. press F11 or click `Toggle Fullscreen` again.

Expected:
browser window should come back to normal from fullscreen (previous state)

Actual:
no response when you press F11 for the second time.

**Comment by safesurfer** [comment]
Yes @calumcraig , this was on Windows. with RC2. But now it looks good on RC3.

**Comment by joshuef** [comment]
@safesurfer can we close this then, with the final release?

**Comment by safesurfer** [comment]
Yes @joshuef, we can close this issue. It's been resolved after the window resize fix in Windows I guess.

**Comment by safesurfer** [comment]
It's resolved, verified by QA
