### ISSUE TITLE
Claim invitation issue: opening/closing tab or switching to another tab opens `invite` url in clearnet browser

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#542]
This issue is related to #539 and #450 

STR:
1. Launch SAFE browser v.0.11.1 RC2
2. Click "Create account" and "Continue"
3. Click "Claim invitation"
4. Close "Authenicator tab" so that now only one tab (which is opened when you click `Claim invitation`) is available on the browser.
5. Try to open a new tab or close the opened tab or switch between two tabs or open a new window and open a new tab from there

Expected:
1. browser should act as expected

Actual:
1. The `invite.maidsafe.net` URL is opened on clearnet browser whenever you perform the actions mentioned in the step 5.

**Comment by RSD1982** [comment]
Also an issue for me. Just downloaded the latest browser 0.11.0 `Claim Invitation Token` page did not close automatically and reopens when I click a new tab.

**Comment by safesurfer** [comment]
QA verified
