### ISSUE TITLE
Getting blank/white screen with only the menu bar, when we try to load `http/s` websites.

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#546]
This issue is related to #450, (see https://github.com/maidsafe/safe_browser/issues/450#issuecomment-452654571)

![issue-546](https://user-images.githubusercontent.com/27578024/51608818-8c130180-1f3e-11e9-8f8a-45d2dfad104d.gif)

STR:
1. Open SAFE Browser v0.11.1-RC3.
2. Open a new tab next to authenticator page
3. Close authenticator page now
4. Make sure only the new tab is exist
5. Try to access any clearnet websites with `http/s` protocol

Expected:
Should show the warning and go back to the last URL

Actual:
The browser goes blank with white screen only with title bar and menu bar.

**Comment by joshuef** [comment]
Part of the issue here:

>Should show the warning and go back to the last URL

There is no last url.

**Comment by safesurfer** [comment]
QA verified.
