### ISSUE TITLE
Unknown and not functioning app icon left in list of authorised apps

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#548]
**Steps to reproduce** (apologies these are vague as this issue occurred in the middle of regression testing and I am not 100% clear on what triggered it):
1. Launch some SAFE apps which require authorisation.
2. Revoke this authorisation from Authenticator in the SAFE browser.
3, Add again and revoke some.

**Expected:**
Icons corresponding to the currently are displayed in the Authenticator screen. When apps are revoked they are removed from this screen and added when authorised.
**Actual:**
An icon with no label can be seen persisting in the Authenticator screen. Clicking it just causes the browser to reload:
![image](https://user-images.githubusercontent.com/44327924/51621131-beffca00-1f2b-11e9-9dd0-dc1b45a7a3ba.png)

**Comment by joshuef** [comment]
Could be related to app naming / odd chars. App info handling in the auth app is kind of brittle.

**Comment by manavbp** [comment]
Closing this issue as its irrelevant now with the new Pweb browser changes.
