### ISSUE TITLE
IP mismatch error thrown intermittently when toggling experiments off / on

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#549]
**Steps to reproduce:**
1. Log into SAFE network.
2. Toggle experiments API off / on a few times.

**Expected behaviour:**
Open apps will ask for re-authorisation, browser refreshes.
**Actual behaviour:**
Intermittently the IP mismatch error message is displayed. User is able to dismiss and continue.
![image](https://user-images.githubusercontent.com/44327924/51623169-fd978380-1f2f-11e9-80e7-31196615ca92.png)
Also attaching browser log from when this occurred.
[Toggle experiments IP message error broweser log]
[Toggle experiments IP message error browser log](https://github.com/maidsafe/safe_browser/files/2788327/Toggle.experiments.IP.message.error.browser.log)

**Comment by joshuef** [comment]
One thing this could be is an error being thrown by the safe app, but is being interpreted as this error (which perhaps it's not)...

----

This could also be related to Experimental mode's app reinitialisation taking some time, while the some parts of the browser expect it to be instant.

So:

Do we need to not inform the store/browser until the Browser's app is confirmed to be toggled to experimental mode?

Do we need some delay and to check for errors?

**Comment by calumcraig** [comment]
During regression testing for v0.11.3 RC1, it appears this behaviour is happening consistently for browser instances created from `yarn prod-dev`:
![image](https://user-images.githubusercontent.com/44327924/54543826-43078880-4996-11e9-8c46-8a1d5d330b92.png)

**Comment by manavbp** [comment]
Closing issue as its irrelevant with the new Pweb browser changes. As the new browser set up connects to the shared/local vault rather than the alpha two network.
