### ISSUE TITLE
Browser stops responding when you hit `Ctrl+N` for three times

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#550]
Browser stops responding when you hit 'Ctrl+N' for three or more times quickly to open a new window.

![issue-new](https://user-images.githubusercontent.com/27578024/51662177-07c18c80-1fd9-11e9-9fee-b954f574a37c.gif)

STR:
1. Open SAFE Browser v0.11.1-RC3
2. Now press `Ctrl+N` quickly for 3 or more times

Expected:
It should open 3 more instances of browser window

Actual:
It stops responding with the error message `Something went wrong extending this component`. recent two windows will be looking like working but actually not.

Need to restart the browser to continue further

**Comment by manavbp** [comment]
this was fixed in #766

**Comment by safesurfer** [comment]
QA verified
