### ISSUE TITLE
Travis: Only build release from Master branch

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#556]
Currently we can trigger a release with any tag, but it may not be from master. We should nail this down to avoid any issues.

**Comment by joshuef** [comment]
QA:

To check this: push a git tag referencing a commit in a pending PR on the repo (which is _ahead of this issues' incporporation into master_ (eg: https://github.com/maidsafe/safe_browser/pull/572).

Push this to the repo and then see if the CI attempts a release.

**Comment by safesurfer** [comment]
I followed the steps @joshuef has suggested, and CI didn't attempt a release, if the tag is pushed from the branches other than master to the repo. I'm moving this to Done.
