### ISSUE TITLE
Improve CI times...

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#565]
Are there tests we can drop? Do we need to run e2e on both dev/master?

What could we reasonably do reduce CI burden without sacrificing stability?

**Comment by joshuef** [comment]
- [ ] Do we need the `rebuild` step?
- [ ] avoid `travis_retry`
- [ ] Do we need to run e2e on Prod / Can we build/package both on ONE machine to avoid duplicating install steps etc.
- [ ] Other things....

**Comment by joshuef** [comment]
The PR #579 is addressing this via:

- [x] Reducing concurrent builds. We now run all E2E against packaged apps. This can be done with the DEV build and flags. Thus avoiding many CI instances / install steps etc.
- [x] Both apps are built on the same system (in DEV env, but PROD, is packaged w/ `NODE_ENV=prod`
- [ ] Prior to package prod, we can remove mock libs.
- [x] Run E2E tests in smaller, easier to repeat batches, so a `travis_retry` is only running a smaller subset of tests incases of a timeout.

**Comment by joshuef** [comment]
QA: Check the RC builds via standard regression tests (should be made automatically via CI).

test release: https://github.com/maidsafe/safe_browser/releases/tag/untagged-b1859df4f8cd247a6c58

**Comment by calumcraig** [comment]
Regression testing is being carried out as usual as part of the release process. A couple of issues have been uncovered:
https://maidsafe.atlassian.net/wiki/spaces/TEST/pages/279838876/v0.11.2

**Comment by safesurfer** [comment]
QA verified
