### ISSUE TITLE
[OSX] Leave padding top left for osx

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#586]
## Prerequisites

Use MacOS

## Expected Behavior

Close/minimize icons should not overlap any UI.

## Current Behavior

https://www.dropbox.com/s/t4buvky59m27icq/Screenshot%202019-02-11%2014.43.56.jpg?dl=0

## Possible Solution

Use constant OS detection to add a class to tab bar to add more padding.

**Comment by calumcraig** [comment]
Built from current master in Mac OS and the issue has been resolved:
![image](https://user-images.githubusercontent.com/44327924/52652000-284c7a80-2ee5-11e9-9cb1-66f6cb32091b.png)
Moving to done.

**Comment by safesurfer** [comment]
Verified with MacOS, moving to done.

**Comment by calumcraig** [comment]
> Verified with MacOS, moving to done.

Did I forget to actually move it? Thanks Srini!
