### ISSUE TITLE
Authenticator not loading after entering login credentials - only confirmed on Windows

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#592]
**Steps to reproduce:**
1. Build browser using
```
NODE_ENV=prod yarn
yarn rebuild
yarn package
```
2. Launch browser
3. Enter valid secret and password credentials to log in

**Expected:**
Authenticator screen with authorised apps is displayed.
![image](https://user-images.githubusercontent.com/44327924/52867955-06980100-313a-11e9-8a2a-0eae625faf87.png)

**Actual:**
Log in screen remains displayed but authorisation message related to the browser is displayed. If user refreshes the page the screen is as expected.
![image](https://user-images.githubusercontent.com/44327924/52867981-144d8680-313a-11e9-96fd-baaa5011bc02.png)
If user refreshes the browser at the stage the correct page is displayed. Seems that the loading of the page doesn't happen correctly initially?

**Further details:**
This only appears to happen on the first instance of running the browser after building it. Also, does not happen everytime. I tried to replicate it and it was happening probably slightly less than 50% of the time. Attaching the output of the dev tools window from launching the browser to the point this issue occurred.
[Browser log authenticaor issue.txt](https://github.com/maidsafe/safe_browser/files/2869864/Browser.log.authenticaor.issue.txt)

FYI @safesurfer

**Comment by manavbp** [comment]
This issue was fixed by #751

**Comment by safesurfer** [comment]
QA verified
