### ISSUE TITLE
Create Unique TabIds and _always_ require them for actions

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#593]
## Current Behavior

We still assume an intended tab for some actions via `activeTab` (some efforts were made to improve this in #567).

Ideally we should always be passing a tab identifier to actions, so that it's _definitively_ occurring with the tab we want.

## Possible Solution

- [ ] Generate a unique tabId for each tab on creation.
- [ ] _always_ use this for identifying tabs in actions.
- [ ] Remove _getActiveTab_ from actions that are not setting a _new_ activeTab.

**Comment by safesurfer** [comment]
QA verified
