### ISSUE TITLE
F5 for reload page

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#596]
**Feature request**

Currently the SAFE browser uses either the refresh button or CTRL + R as options to reload the pages - these are common (Firefox and Chrome anyway) browser navigation methods.

Can we add simply F5 to reload - again both Chrome and Firefox currently have this option. (From a personal point of view this is the method I prefer to use to reload a page.)

**Comment by calumcraig** [comment]
Another similar shortcut - F11 for full screen toggle - is already implemented.

**Comment by hunterlester** [comment]
Surprisingly not straight forward.
`F5` currently refreshes the the whole browser window and all tabs.
`globalShortcut.unregister('F5')` is not working as I'm intending.
What I'm looking for is some kind of on `reload` event where `event.preventDefault()` can be called.

**Comment by safesurfer** [comment]
Tested this card, the `Reload` shortcut `F5` is not updated in rightclick context menu. It still shows `Ctrl+R` on windows
![image](https://user-images.githubusercontent.com/27578024/58554500-b9492680-8234-11e9-9717-991d09d98ac3.png)

**Comment by manavbp** [comment]
Resolved in Browser v0.14.0 fixed in #841
