### ISSUE TITLE
Right click for navigation options (back / forward / reload)

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#597]
**Feature request**

In Firefox and Chrome, right mouse click gives a context menu which includes the navigation options of back, forward and reload:
Chrome:
![image](https://user-images.githubusercontent.com/44327924/53028674-352a1a80-345f-11e9-92b1-72dca0473ca3.png)
Firefox:
![image](https://user-images.githubusercontent.com/44327924/53028700-46732700-345f-11e9-84e6-d658cfa4e0e8.png)
Currently the only right click option in SAFE Browser is "Inspect element" - can navigation options (which exist as buttons / menu items) be added to the right click menu?

**Comment by hunterlester** [comment]
Recommending that this task not be completed until we complete migration from `webview`'s to `BrowserView`'s as view architecture will change drastically.

**Comment by joshuef** [comment]
As I'm not sure about Browser View's prospects re: zindexing etc, I'm gonna fire into this as it's largely just adding some menu options.

**Comment by joshuef** [comment]
Changes made and these have been added over here: https://github.com/joshuef/safe_browser/tree/FeatContextMenu

But waiting on an updated `electron-context-menu` (https://github.com/sindresorhus/electron-context-menu/pull/67)

**Comment by safesurfer** [comment]
I can now see the menu options in the right-click context menu. (Back, Forward, Reload, Open New Tab, etc.)
