### ISSUE TITLE
"Open link in new tab" opens at end of currently open tabs.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#599]
**Steps to reproduce:**
1. Launch SAFE Browser.
2. Load a page with links to other pages.
3. Right click "open link in new tab" or CTRL + click on a link.

**Expected behaviour:**
New link will open in a tab next to currently selected tab.
**Actual behaviour:**
New link opens at end of current list of tabs - on right hand side of browser.
![image](https://user-images.githubusercontent.com/44327924/53083044-0f9c2000-34f6-11e9-9d65-60050b888e7a.png)
![image](https://user-images.githubusercontent.com/44327924/53083060-188cf180-34f6-11e9-81bf-6ce929f87769.png)

**Comment by hunterlester** [comment]
Making this issue dependent on #593 
Tabs definitely need unique ID's for this task, otherwise views are crashing.

**Comment by S-Coyle** [comment]
Verified that this is now resolved on the dev branch (tested on Ubuntu)
