### ISSUE TITLE
Tyring to build for mock - I'm getting 

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe_browser#60]
Operation System: Debian 8
Beaker Version: Latest git checkout dev (there's no about box to check)

I've build the browser for mock as in the readme (and I can see it is building with ```cargo build --release --features "use-mock-routing"```). When I run the browser all looks fine but if I try to create an account or login it fails, and both give similar errors in the browser console (below).
 
### Browser Console:
```
action CREATE_ACC @ 19:00:33.952
core.js:102 action CREATE_ACC_REJECTED @ 19:00:37.632
import-api.js:203 Uncaught (in promise) Error: {"error_code":-14,"description":"Core error: Blocking operation was cancelled"}(…)
core.js:102  action @@router/LOCATION_CHANGE @ 19:03:22.764
core.js:102  action @@router/LOCATION_CHANGE @ 19:03:22.777
core.js:102  action CLEAR_AUTH_ERROR @ 19:03:22.816
core.js:102  action @@router/LOCATION_CHANGE @ 19:03:22.842
core.js:102  action CLEAR_AUTH_ERROR @ 19:03:35.340
core.js:102  action LOGIN @ 19:03:35.375
core.js:102  action LOGIN_REJECTED @ 19:03:41.310
import-api.js:203 Uncaught (in promise) Error: {"error_code":-14,"description":"Core error: Blocking operation was cancelled"}(…)onCbReply @ import-api.js:203onIPCMessage @ import-api.js:118emitMany @ events.js:127emit @ events.js:201
```

**Comment by theWebalyst** [comment]
Just noticed in the linux console:

```
WARN 19:03:41.216934343 [safe_core::client mod.rs:1172] Could not connect to the Network. Unexpected: Ok(Event::Terminate)
```

**Comment by krishnaIndia** [comment]
@theWebalyst 
Can you try removing the node_modules and app/node_modules and then try running the following commands,
```
NODE_ENV=dev npm i && npm run rebuild && npm run build && npm run package
```

This should get the browser built with mock. But the library used by this command is not the latest master.

You can swap the locally built libraries for authenticator and DOM apis in `app/node_modules/beaker_plugin_safe_authenticator/dist` and `app/node_modules/safe_app/src/native`

We will get the dependencies updated to the latest safe_client-libs master branch soon.

Also please note, compile safe_app and authenticator with the `testing` feature

`cargo build --release --features "testing use-mock-routing"`

**Comment by theWebalyst** [comment]
Thanks @krishnaIndia 

I thought I'd try this as I was having [problems building hunter's safe_browser fork](https://safenetforum.org/t/building-dev-mode-safe-browser-debian-8/14679?u=happybeing) to use with his safe_dom_api_playground so probably I should be patient (not my best quality) and wait for him to help with that.

**Comment by krishnaIndia** [comment]
The issue for building with mock is resolved. Thanks @theWebalyst
