### ISSUE TITLE
"Download sample applications here..." link takes user to a deprecated GitHub repo.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#601]
**Steps to reproduce:**
1. Launch browser and log in with valid SAFE network credentials for the first time (this can also be reproduced by revoking previously granted access to the SAFE browser).
2. Click on Download sample applications here... clearnet link.
3. Default clearnet browser is launched with the link: https://github.com/maidsafe/safe_examples/releases
![image](https://user-images.githubusercontent.com/44327924/53088967-29902f80-3503-11e9-84d4-6c7cef43e95b.png)

**Expected result:**
Link takes user to a an up to date repo where they can find example SAFE applications.
**Actual result:**
Link takes user to a deprecated repo.
![image](https://user-images.githubusercontent.com/44327924/53089026-53e1ed00-3503-11e9-88c1-2d2323bd831b.png)

**Comment by manavbp** [comment]
Closing this issue as the authenticator has been removed with the new Pweb browser changes
