### ISSUE TITLE
Bookmarks and history not clearing after log out

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#602]
**Steps to reproduce:**
1. Launch SAFE browser and log in with valid SAFE credentials.
2. Browser / create bookmarks or read existing data from SAFE network.
3. Click "logout" 

**Expected results:**
Bookmarks and history will clear.
**Actual results:**
Data from step 2 above persists.

This issue has been seen previously https://github.com/maidsafe/safe_browser/issues/325

**Comment by manavbp** [comment]
fixed by #605

**Comment by calumcraig** [comment]
Regression has been resolved by RC2. Verified working as expected, moving to done.
