### ISSUE TITLE
when we click on address bar, text is selected on all other opened instances

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#612]
when we click on address bar, text is selected on all other opened instances of browser.

STR:
1. open browser and open a new window
2. click address bar of any of the windows
3. the text on the address bar of other window is selected

**Comment by joshuef** [comment]
This should be sorted as part of #593

**Comment by manavbp** [comment]
This issue was fixed by #751

**Comment by safesurfer** [comment]
QA verified
