### ISSUE TITLE
WebID dropdown not working

### ISSUE THREAD

**Issue by JPL1** [maidsafe/safe_browser#620]
Browser 0.11.2 Debian Linux and Windows 10

The dropdown says 'no WebIDs found' even though I have created some. Possibly related to #320

![web-ids](https://user-images.githubusercontent.com/12783198/53647515-a1fa9d00-3c35-11e9-8d33-0bb394881729.png)

**Comment by theWebalyst** [comment]
I have this issue on Ubuntu 18.10 (SAFE Browser 0.11.2 dev build).

Any news / workarounds? I need this to develop stuff! Cheers.

**Comment by calumcraig** [comment]
Apologies for not responding to this issue previously. This is a know bug which was reported previousy in the forum:
https://safenetforum.org/t/webids-not-showing-in-browser/27499
The devs are currently looking at it and a fix is in progress - not sure when they'll be able to deliver it at the moment but as soon as poss.

**Comment by bochaco** [comment]
As a workaround, for me it works by first enabling experimental APIs and then loging in the Authenticator. 
Although I know that doesn't work for others, but worth a try.

**Comment by theWebalyst** [comment]
Thanks folks.

@bochaco unfortunately that workaround doesn't make any difference for me but I can fudge the code for now, so not urgent for me.

**Comment by joshuef** [comment]
I think I see the problem here with some post-refactor code.

Should have a commit for you to check out shortly @calumcraig !

**Comment by calumcraig** [comment]
Testing on v0.11.3 RC. This issue has been resolved - clicking on the WedID Manager icon in the address bar now gives us a drop down menu showing the existing WebIDs plus an option to open the Manager app:
![image](https://user-images.githubusercontent.com/44327924/54443999-c5dfd780-4739-11e9-9ab2-0b3e533477ff.png)
Tested on Linux Mint 19 Cinnamon.
