### ISSUE TITLE
ubuntu 18.04 ./safe-browser: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rid-dim** [maidsafe/safe_browser#627]
i just downloaded the compiled browser and tried to start it on ubuntu 18.04

i had to manually

> sudo apt install libgconf2-4

to get it up and running; just thought i'd mention it

**Comment by calumcraig** [comment]
Hi rid-dim,

Thanks for reporting this - can you just confirm what version of the browser you downloaded? Did you get the error message when you tried to launch the browser?

I'm running Mint 19 which is based on Ubuntu 18.04 and not having any issues - I'll try also in my Ubuntu VM.

**Comment by calumcraig** [comment]
Hi again,

Yes, I am seeing the same issue with my Ubuntu VM. I'll escalate this.

**Comment by rid-dim** [comment]
sorry was too slow to get back to you - but since you saw the same effect i guess you're on it =)

**Comment by calumcraig** [comment]
Hi, NP, and yes, I worked out it was the most recent version of the app. The main browser dev is off today so I haven't had any response to this yet - will follow up tomorrow. It's not blocking you at least which is good.

**Comment by calumcraig** [comment]
**Steps to reproduce:**
1. Environment - Ubuntu 18.04.
2. Download SAFE Browser v0.11.2 for Linux https://github.com/maidsafe/safe_browser/releases/download/v0.11.2/safe-browser-v0.11.2-linux-x64.zip
3. Attempt to launch browser from A) CLI or B) File manager.

**Expected results:**
SAFE Browser launches OK
**Actual results:**
A) Browser does not launch and user is presented with the feedback:
![image](https://user-images.githubusercontent.com/44327924/54271889-57085000-457a-11e9-8801-eaa33baf4382.png)
B) Browser does not launch, user is given no feedback.

**Comment by calumcraig** [comment]
A workaround is possible:
```sudo apt-get install libgconf*```
but as noted, if user only attempts to launch from file manager they will not get the feedback and most likely will be unaware of this.

**Comment by calumcraig** [comment]
Just for confirmation - the issue was originally reported on v0.11.2 and is still present in v0.11.3 RC1.

**Comment by calumcraig** [comment]
I don't know if you have been following the board @rid-dim but the guys rolled out a fix to this issue that broke other things so had to roll it back. This issue is still on the radar to sort properly but it won't be in the next release coming out this week - v0.11.3. 

As you mentioned in the OP though the workaround is relatively straight forward and is listed in the pre requisites on the README.

**Comment by rid-dim** [comment]
All good - with hint in the readme should be good enough for anybody - everything is still in alpha stage ;ľ

**Comment by calumcraig** [comment]
Yeah, we'll get it fixed - want the browser to be as user friendly as poss - but didn't make it for this release! We're releasing basically monthly though these days so hopefully won't be too long.

**Comment by joshuef** [comment]
Closing as we've this documented in the readme

**Comment by safesurfer** [comment]
The solution is explained in the readme of safe_browser repo. And I've installed `libgconf-2-4` as mentioned in the document and tested. It works fine and moving it to Done.
