### ISSUE TITLE
Webview crashing on interaction with redux dev tools

### ISSUE THREAD

**Issue by manavbp** [maidsafe/safe_browser#630]
Steps to reproduce
1. Launch the safe browser prod or mock
2. Open up the redux dev tools
3. Interact with the redux dev tools
4. Any interaction with the browser causes the webview to crash

**Comment by joshuef** [comment]
I do not see this on MacOS or linux.

@hunterlester can you repro?

also, @manavbp can you check if this is still happening w/ latest dev?

**Comment by hunterlester** [comment]
@joshuef Unable to reproduce.

**Comment by safesurfer** [comment]
Unable to reproduce and it seems non-relevant
