### ISSUE TITLE
Toggling full screen (F11) is not working, after opening a New Window at least once.

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#633]
Toggling full screen, is not working, throws the following error, if you have previously opened a `New window`. If you toggle full screen on Main window, it toggles the newly opened window, not in the main window.

![image](https://user-images.githubusercontent.com/27578024/54435305-309f0c00-4756-11e9-9894-233b6380f81a.png)

### Scenario 1

1.  Open Browser (dev/prod), click `New Window` and close the newly opened window
2.  Try toggling full screen. It throws above error.

### Scenario 2

1. Open Browser and click `New Window`, leave the newly opened window and return to main window.
2. Try toggling full screen, it throws the above error and toggles the newly opened window to fullscreen.

**Comment by calumcraig** [comment]
Can replicate this behaviour on Linux Mint 19 Cinnamon.

**Comment by safesurfer** [comment]
QA Verified
