### ISSUE TITLE
Performance issue when 1+ browser window open - MacOS

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#636]
**Steps to reproduce:**
1. Launch browser and open more than one browser window.
2. Open more than one tab in each window and load some pages.

**Expected:**
Performance should not be adversely affected.
**Actual:**
Performance seriously impacted - browser process seen at around 100% of processor. Browser becomes extremely unresponsive, clicking on menu, changing tab etc doesn't work / takes excessively long.
<img width="1427" alt="Screenshot 2019-03-19 at 10 55 26" src="https://user-images.githubusercontent.com/44327924/54602866-ba8ef380-4a3a-11e9-9d35-32a55dad120f.png">
Closing one browser window (after a delay of several seconds) will alleviate the issue and performance returns to normal:
<img width="1418" alt="Screenshot 2019-03-19 at 11 02 14" src="https://user-images.githubusercontent.com/44327924/54602873-c11d6b00-4a3a-11e9-8990-4159bb97892f.png">

**Comment by calumcraig** [comment]
Above behaviour observed on MacOS.

The same scenario in Linux Mint shows no effect on performance:
![image](https://user-images.githubusercontent.com/44327924/54603519-6d138600-4a3c-11e9-89ee-a25f9896dfb9.png)

**Comment by safesurfer** [comment]
I've tried opening 5+ browser windows and many tabs in one window, as you said it went to 68% of CPU from 10% for few seconds, but it dropped to 8% and still it is in 8-10%. I didn't close any of the browser windows. still they are opened

**Comment by joshuef** [comment]
this was fixed in #766

**Comment by calumcraig** [comment]
Tested latest commit on `dev` branch: `865e1b3c (HEAD -> dev, origin/dev, origin/HEAD) chore(deps-dev): bump eslint-plugin-jest from 22.5.1 to 22.6.4`

Test machine - QA Mac:
``Model Name:	iMac
  Model Identifier:	iMac11,3
  Processor Name:	Intel Core i3
  Processor Speed:	3.2 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	12 GB
  Boot ROM Version:	96.0.0.0.0
  SMC Version (system):	1.59f2
  Serial Number (system):	W80520B5DB6
  Hardware UUID:	33D60AE5-DFAC-58BB-B43D-576149FE4F32```

**Comment by calumcraig** [comment]
Opened five tabs in the browser, including one playing a video. No discernible effect upon performance could be seen. Indeed the highest drain on the CPU at the time was the instance of the Safari browser I had open at GitHub.

**Comment by calumcraig** [comment]
The only observation I would make is that the number of threads for the processes associated with SAFE Browser seems quite high. Is this anything that needs attention @joshuef @hunterlester ?

**Comment by calumcraig** [comment]
This issue (performance) has been resolved so moving this to done.
