### ISSUE TITLE
Multiple windows, flickering when entering on address bar

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#639]
- OSX

## Expected Behavior

Focus should not leave selected window.

## Current Behavior

- Two windows open
- enter a url, press enter, both windows flicker into focus and out for a half a second

## Possible Solution

I'd wager this is related to our tab reducer issues. @manavbp FYI

**Comment by joshuef** [comment]
Actually this is same issue as #636

**Comment by calumcraig** [comment]
Duplicate of #636, nothing to test, moving to done.
