### ISSUE TITLE
Linux packaged browser failing to launch.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#640]
**Steps to reproduce:**
1. Clone Safe_browser repo after PR #637 
2. Follow steps https://github.com/maidsafe/safe_browser#compiling to package the browser locally.
3. Navigate to the release folder and try to launch browser with `./safe-browser`

**Expected result:**
Browser will launch OK
**Actual result:**
Browser fails to launch, error message is returned: `Segmentation fault (core dumped)`
![image](https://user-images.githubusercontent.com/44327924/54759237-928fc380-4be5-11e9-9f85-c941e21fb408.png)
**Environments:**
This has been replicated in Ubuntu 18.04 VM and Linux Mint 19 Cinnamon native machine.

**Comment by hunterlester** [comment]
@calumcraig I'll continue to try to reproduce. Until then, I want to look at that core dump.

Do you have a core dump file located at `/usr/share/apport/apport`?
If not, `cat /proc/sys/kernel/core_pattern` should give you the location of the dumped memory core.

If there are none, then `apport` may need to be started first.
`systemctl start apport`

**Comment by hunterlester** [comment]
@calumcraig Do you also receive a segfault with this package? https://github.com/hunterlester/safe_browser/releases/tag/libgconf

**Comment by hunterlester** [comment]
@calumcraig [UPDATE]: Scratch that. I'm able to reproduce.

**Comment by calumcraig** [comment]
@hunterlester I can see you've been working on this (for me) overnight - I take it you don't need me to do anything further? If you do just let me know.

**Comment by calumcraig** [comment]
Can confirm that the roll back of PR #637, PR #641 has resolved this issue. SAFE Browser launches as expected on Linux Mint 19.

Tested on Ubuntu 18.04 and behaviour has returned to the previous - #627 is still seen. Workaround (as described in browser README) resolves the issue: `sudo apt-get install libgconf-2-4`.
