### ISSUE TITLE
Use testcafe as replacement for spectron where possible

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#646]
Peruse(Browser ui) tests have been ported to testcafe.

QA:

- `yarn`
- `yarn cafe-e2e`

Spectron tests are now _disabled_ on CI. From now on before release / for testing we should run these tests locally as part of the sanity check (until they are migrated to testcafe / we set up DOM site testing):

```
   - yarn test-e2e __e2e__/peruse.spec.
   - yarn test-e2e __e2e__/settingsMenu.spec.
   - yarn test-e2e __e2e__/navigation.spec.
   - yarn run test-e2e e2e/safe-auth
   - yarn run test-e2e e2e/safe-mock
   - yarn run test-e2e e2e/safe.spec
```

**Comment by safesurfer** [comment]
QA Verified
