### ISSUE TITLE
authenticator has unexpected behaviour when granting access to a not-existing "standard"-container

### ISSUE THREAD

**Issue by rid-dim** [maidsafe/safe_browser#656]
i just thought i'd mention that the authenticator kind of fails when someone asks for access for a non-standard container (in this case with the name '_musica' - that i am limited to a couple of containers listed here:

https://forum.safedev.org/t/safe-network-api-getting-started-draft/726

wasn't what i expected and i thought i made a mistake somewhere else because it worked fine with '_music' ... why does the authenticator ask me to grant the permission if i can't grant those rights?

![image](https://user-images.githubusercontent.com/23142572/55672367-76a14880-589a-11e9-9a4c-629cfb4ee76c.png)

**Comment by joshuef** [comment]
Aha, righto. 

This isn't passed over to the auth lib until the request is authed to be made.

We need to whitelist container names I think, and throw otherwise.

Thanks @rid-dim 👍 

----

@lionel1704 @m-cat Do we have some standard errors we should be throwing with malformed container requests that you're aware of? (Do we currently throw for this in the authenticator lib?)

**Comment by m-cat** [comment]
> Do we have some standard errors we should be throwing with malformed container requests that you're aware of? (Do we currently throw for this in the authenticator lib?)

Yes, we use `ERR_NO_SUCH_CONTAINER`. There is also `ERR_CONTAINERS_DENIED` which you might be interested in, but it's not currently used in SCL.

**Comment by bochaco** [comment]
If I understand correctly this would add details into the browser/authenticator which shouldn't be there, the list of default containers are maintained by the SCL, if we add any type of verification in any other layer we would have to keep them all in sync, probably not a big deal but not ideal. I wouldn't make any checks on any layer to verify the containers are the supported ones but in SCL.

Also, I recently realised that SCL is not failing to authorise a containers auth request which contains non-existing default containers in the list, for example the following step in a test I was working on doesn't fail as expected (I created such a request with `{ _invalid_container: ['Insert'] }` as the set of permissions being requested): https://github.com/maidsafe/safe-authenticator-cli/pull/30/files#diff-b4aea3e418ccdb71239b96952d9cddb6R682
