### ISSUE TITLE
`Tests` Menu is appearing on Production version of Browser on Windows

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#685]
The new `Tests` Menu, next to `Help` Menu, is appearing on Production version of Browser on Windows.

![Annotation 2019-04-22 183853](https://user-images.githubusercontent.com/27578024/56501990-7e195080-652e-11e9-8320-b568148762af.png)

**Comment by joshuef** [comment]
closed by 5aabb1a62e4381ff306f4ed0fbeb1c8e10d10712

**Comment by safesurfer** [comment]
QA verified
