### ISSUE TITLE
Clicking `http` url from safe site twice, the page goes two steps back

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#689]
When I click http url once, in `safe://safenetworkprimer` it shows the error popup, but if I click the same link twice, the page goes two steps back, if I click thrice, goes three steps back, and so on.

STR:
1. Open browser and a new tab, access some safe site which has http links, eg: `safe://safenetworkprimer`
2. click some chapter, and click `http` link. It shows error popup saying `the url is blocked`
3. try click the same link twice, it goes two steps back, which is the home page `safe://safenetworkprimer`
4. try click the same link thrice, it goes three steps back, which is `about:blank` and so on.

**Comment by joshuef** [comment]
Ah, the actual issue here seems to be clicking the same link twice throws an error for a `safe:` link, which it should not (and is then sending us back in the history)

**Comment by safesurfer** [comment]
QA verified
