### ISSUE TITLE
Close developer tools window - window reopens

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#692]
**Steps to reproduce:**
1. Launch browser.
2. Toggle open developer tools window, either `View` >> `Toggle Developer Tools` or `CTRL + ALT +I`.
3. Switch back to main SAFE browser window and attempt to close developer tools - again either by the menu option or the keyboard shortcut.

**Expected:**
Developer tools window remains closed.
**Actual:**
Developer tools window reopens by itself.
https://maidsafe.slack.com/files/UENBNQHSA/FHUMXQZHQ/2019-04-25_10-11-42.mp4

**Comment by joshuef** [comment]
blocked until #593 , where we should more easily be able to pass around 'openDevTools' for a given window/active tab combo

**Comment by joshuef** [comment]
this was fixed in #766

**Comment by manavbp** [comment]
Fixed in #781
