### ISSUE TITLE
External SAFE links not opening consistently after first instance of SAFE browser has been closed.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#720]
**Steps to reproduce:**
1. Launch SAFE browser and open 1+ browser windows.
2. Close the first instance of the browser (the window with the authenticator).
3. Click on SAFE links in regular browser.

**Expected behaviour:**
Links will open the corresponding SAFE sites in the SAFE browser when clicked.
**Actual behaviour:**
Links do not open immediately. If user _only_ clicks on SAFE links in regular web browser the SAFE sites will not open. User needs to click _back_ to the SAFE browser before SAFE links open.

**Comment by joshuef** [comment]
@calumcraig do you see this on macOs?

at the bleeding edge of `dev` I cannot repro this. But i'm not sure if it was happening on mac anyway...

**Comment by calumcraig** [comment]
The above behaviour was observed on Linux (Mint 19 Cinnamon).

Same behaviour is seen on Windows.

**Cannot** reproduce on MacOS.

**Comment by joshuef** [comment]
Thanks! That's cleared it up for me some 👍

**Comment by joshuef** [comment]
Closing as no longer an issue

**Comment by safesurfer** [comment]
QA verified on Windows.
