### ISSUE TITLE
`dev` branch: BrowserWindow does not open

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_browser#724]
Only developer tools windows open.

## Prerequisites

- [ ] Windows
- [ ] `dev` branch

## Expected Behavior

Appearance of BrowserWindow

## Steps to Reproduce (for bugs)

1. Checkout `dev` branch on Windows

2. `yarn` -> `yarn rebuild` -> `yarn build` -> `yarn mock-dev`

3. Alternatively, `yarn package` and execute binary.

3. Observe lack of BrowserWindow

- Operating System and version : Windows 10

**Comment by joshuef** [comment]
@hunterlester this sorted on latest dev?

**Comment by hunterlester** [comment]
@joshuef No, but it will sort itself out when #723 is merged. See my comments there about current issue on Windows.

**Comment by hunterlester** [comment]
Resolved as of https://github.com/maidsafe/safe_browser/commit/952f83cde032d3619200f136fae48bc531cb6119
