### ISSUE TITLE
[dev] Link navigation issues

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#726]
navigating to: safe://playground.dapp

Left hand side links do not work.

Right clicking and opening a new window throws a deathly error.

**Comment by joshuef** [comment]
@hunterlester looks like the playground is throwing some errors w/ electron 4. Would you be able to dive in there?

**Comment by joshuef** [comment]
the second part here is `open in new tab` actually being available for non links. So that's what I need to sort there

**Comment by safesurfer** [comment]
QA verified, I'm able to navigate through the apis from left hand side bar.
