### ISSUE TITLE
index.html not automatically read or added

### ISSUE THREAD

**Issue by tomcarlson** [maidsafe/safe_browser#73]
Operation System: Win7
Beaker Version: 0.3.0

When typing in a URL to a site, for example, safe://portlandspirit, the URL is rewritten so that it becomes safe://portlandspirit/index.html  This is ugly.  It should not rewrite the URL and read index.html automatically.

When clicking on a link that does not include index.html, the index.html is not added as it was when the URL is typed.  Instead, a "ERR_NOT_IMPLEMENTED" error is displayed.  index.html should not need to be in the URL, but it does need to be, then it should be automatically added when missing so it is consistent with the behavior that happens when you type an URL

**Comment by krishnaIndia** [comment]
We will resolve this issue in the next version update. Thank you!
