### ISSUE TITLE
Closing Browser Tab should free up SAFE resources from App running in Tab

### ISSUE THREAD

**Issue by tomcarlson** [maidsafe/safe_browser#75]
Operation System: Win7
Beaker Version: 0.3.0

I have tried the [sample application #3 ](https://forum.safedev.org/t/safe-network-api-getting-started-draft/726).  I put it at **safe://app.portlandspirit**

Since I can only refresh the page once or twice before I get an error, there is apparently a problem with the script releasing it's app tokens and therefore  burning through Test 17's limited separate active apps.

However, there will always be misbehaving apps.  The user should be able to close the browser tab, and free up any SAFE resources that the app in that browser tab was using.  

Currently, closing the browser tab of the offending app and opening a new one does not clear the error, resulting in the need for a complete browser restart.

**Comment by krishnaIndia** [comment]
We have a [task](https://maidsafe.atlassian.net/browse/MAID-2113) for clearing handles in JIRA. We will be picking this one sooner

**Comment by krishnaIndia** [comment]
Should be resolved in the latest master and in the [0.4.0 release](https://github.com/maidsafe/safe_browser/releases/tag/0.4.0)

Thanks @tomcarlson
