### ISSUE TITLE
Not possible to go back multiple pages in the history

### ISSUE THREAD

**Issue by AxlMaid** [maidsafe/safe_browser#77]
Operation System: Mac OS X
Beaker Version:

I can only go back or forward in the navigation history 1 page at a time.
It should be possible to go back or forward multiple pages with a long press on the back/forward button in the navigator, just like Chrome does.

Alexandre

**Comment by krishnaIndia** [comment]
This is part of the known limitations stated in the previous release. However, we have a [task](https://maidsafe.atlassian.net/browse/MAID-2121) in JIRA for supporting the same.
