### ISSUE TITLE
Shouldn't the demo applications just open as new tabs in the browser?

### ISSUE THREAD

**Issue by AxlMaid** [maidsafe/safe_browser#78]
Operation System: MacOSX
Beaker Version:

It would be nice if all applications (e.g. Web Hosting Manager or SAFE Mail Tutorial) would open as new tabs in the SAFE Browser instead of separate new applications. After all these are web applications like websites.
In the end users may be lost if there are many new programs running on the computer rather than all within the browser. Plus killing all the SAFE apps at once would be easier if all would be contained in the SAFE Browser.

Let me know if you have questions.

Axl

**Comment by krishnaIndia** [comment]
The example applications are to demonstrate the usage of the safe_app_nodejs API usage. These examples show case the usage on hoe to use the nodejs API directly. For web applications, we have the [DOM API examples](https://forum.safedev.org/t/safe-network-api-getting-started-draft/726) to try.

The idea is to show case the usage of various APIs and approaches.
