### ISSUE TITLE
`windowsTabs` is undefined

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_browser#809]
Observing error:
```
Something went wrong extending Zr
{"message":"Cannot read property 'forEach' of undefined","name":"TypeError"}
```

`windowsTabs` can be undefined here when running packaged browser: https://github.com/maidsafe/safe_browser/blob/dev/app/components/Browser/Browser.tsx#L91

**Comment by safesurfer** [comment]
QA verified
