### ISSUE TITLE
History timestamp not correct time.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#853]
**Steps to reproduce:**
Testing SAFE Browser v0.14-RC, macOS.
1. Launch browser and browse some pages.
2. Open history tab.

**Expected:**
Time stamps of pages visited are correct.
**Actual:**
![image](https://user-images.githubusercontent.com/44327924/59859771-4fc0c180-9375-11e9-9c2b-568dbc1831ed.png)
Time stamps are an hour before the actual time. In the screenshot I have just visited the cat site which shows as 15:00 whereas actual local time is just after 16:00. Presumably this is related to the fact that current local time is BST which is GMT+1?

**Comment by manavbp** [comment]
Hey @calumcraig! The timestamps for history in the browser at the moment are in GMT and not specific to local time zones

**Comment by calumcraig** [comment]
Hi @manavbp if this is expected behaviour I'll close this, that's fine.

**Comment by calumcraig** [comment]
As noted above, this is currently expected behaviour, timestamp feature not yet supporting accurate local time.

Closing this bug
