### ISSUE TITLE
History timestamps have both AM / PM and are in 24 hour clock format.

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#854]
Expected:
The time visited for pages in the history record is recorded either as (eg) 3:00 PM _or_ 15:00.
Actual:
The time visited for pages in the history record is recorded with **both** 12 and 24 hour clock styles.
![image](https://user-images.githubusercontent.com/44327924/59860227-35d3ae80-9376-11e9-8b33-b4b2363a2192.png)

**Comment by safesurfer** [comment]
QA verified and confirmed getting 12 hrs clock format with locale time
