### ISSUE TITLE
RIght click Inspect element broken

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#860]
Related to https://github.com/maidsafe/safe_browser/pull/840/commits/e452936ae9f8182bd3fe1d1b86fe2ee0d2fddbf0?file-filters%5B%5D=.ts#diff-501b971653b4f8f377038d0974a90d7fL64

## Wanted

- [x] In browser dev modes (`yarn dev`, `yarn prod-dev`), we should be able to inspect BOTH, the browser UI, _and_ the tab's DOM. This should be available via the right click context menu.
- [x] Packaged we should ONLY be able to inspect the tab's DOM. This should be available via the right click context menu.

**Comment by safesurfer** [comment]
QA verified
