### ISSUE TITLE
Running AppImage file, throws IP mismatch error on Ubuntu

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#861]
AppImage file is available, when we build manually. Running the AppImage launches the browser, while launching it throws `IP mismatch` error even though IPs are same. So, not able to access any sites, but with `Setup is Incomplete` error.

It is confirmed with Ubuntu and Mint distro (confimed by @calum).

**Comment by manavbp** [comment]
Resolved with #950
