### ISSUE TITLE
App auth pop up appears on every browser window instance

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#878]
**Steps to reproduce:**
1. Launch browser, log into SAFE.
2. Open more than once browser window.
3. Attempt to open a SAFE web app that requires authorisation: eg. safe://to-do

**Expected:**
Authorisation pop up only appears on one browser window (authenticator window / window that app will open in? - TBC).
**Actual:**
Pop up up appears in all browser window instances. The actual one that is clicked will clear but all other pop ups persist (until closed by user):
![image](https://user-images.githubusercontent.com/44327924/60327076-e3504e80-9982-11e9-9ff3-fc79bd430514.png)

![image](https://user-images.githubusercontent.com/44327924/60327082-e77c6c00-9982-11e9-91ec-0eb1858f0805.png)

**Comment by manavbp** [comment]
Closing this as there is no authenticator with the new Pweb browser. This issue can be referenced to #517.
