### ISSUE TITLE
Issue with fetching webIds

### ISSUE THREAD

**Issue by manavbp** [maidsafe/safe_browser#888]
The SAFE Browser throws a promise error while trying to fetch webIds.

Steps to reproduce-
1) Launch safe-browser using `yarn prod-dev`
2) Login to the Authenticator
3) Once logged in toggle experimental API's
4) try to fetch webId's
5) In devtools a promise error throws while trying to fetch webId's

**Comment by S-Coyle** [comment]
Note that this issue does not appear to happen in the packaged version of the browser. Only happens when built from code

**Comment by theWebalyst** [comment]
I'm pretty sure I see this with the pre-built mock browser 0.14.0

**Comment by S-Coyle** [comment]
Thanks for the update @theWebalyst - I'll verify

**Comment by S-Coyle** [comment]
Wasn't able to replicate this on latest v0.14.1 release (packaged version) on either dev or non dev package. I'm on macOS v10.14.5.
@calumcraig when you get a sec could you see if you can replicate with latest packaged browser on Linux?

**Comment by calumcraig** [comment]
@S-Coyle Tried both dev and non dev on my Linux Mint 19 machine and am also unable to reproduce. This is SAFE Browser v0.14.1

**Comment by manavbp** [comment]
As at the moment, there are no API's for creating/fetching webIds in the pweb browser.
