### ISSUE TITLE
What's the specification of the Javascript Runtime used in the browser

### ISSUE THREAD

**Issue by lingnand** [maidsafe/safe_browser#914]
I'm intending to develop a web app on Safe, but I can't find any specification on the supported javascript runtime.

As I also consider allowing the web app to run in normal browser e.g., Chrome, ideally there is a large overlap on what's supported and most of the libs on Node.js can still be used directly.

A clear guide on the differences and similarities with mainstream browser re javascript runtime would be welcome.

**Comment by joshuef** [comment]
It's running Electron v4 (https://github.com/electron/electron/releases/tag/v4.0.0), Chromium `69.0.3497.106`, Node `10.11.0`, and V8 `6.9.427.24`

So there should be significant overlap with modern js environments. 

Hope that helps!

**Comment by lingnand** [comment]
Thanks; I'm not very familiar with electron, does it expose all api from Chromium? e.g., can I expect the same set of functions on the `window` object as that in Chromium?

Also, does Safe disable any functionalities for security reasons?

**Comment by joshuef** [comment]
You're best bet is diving into electron docs: https://electronjs.org/docs/tutorial/about

It's more or less aiming to provide chromium APIs but there are specific cases where they diverge some. (eg: extensions).

The SAFE Browser itself blocks `eval`, and `http` reqs for example.
