### ISSUE TITLE
Does the browser need to implement CSP rules? 

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe_browser#92]
Operation System:
Beaker Version:

I'd like to understand whether we need SAFE Browser to implement Content Security Policy rules in order to protect SAFE users from attacks similar to XSS (eg malware inserted into the content of a SAFE website through comments etc).

I suspect that we will need to do this, as it's increasingly being done in mainstream browsers, in which case it would be best to do it sooner rather than later or a lot of apps and websites will break when it is introduced. 

Some discussion here: 
https://forum.safedev.org/t/safe-network-api-getting-started-draft/726/16?u=happybeing

**Comment by hunterlester** [comment]
Thank you for bringing this up. I'm going to create a task to review CSP.
My initial impression is that beaker browser incorporates a CSP equivalent by default.

When I was building my `dev-mode` browser monstrosity, I had to explicitly ask the browser to allow me to run `unsafe-eval`, here: https://github.com/maidsafe/safe_browser/blob/master/app/shell-window.html#L7

**Comment by theWebalyst** [comment]
OK, I didn't know that. What I think atm is that it is weaker than we may want then (eg it asked inline scripts and CSS for example), so a comparison with Chrome, Firefox CSP details would be interesting, and also a review of each option and whether it is relevant to Safenetwork. I don't think I understand it well enough myself, but reading up a bit when I was falling foul of the CSP rules maidsafe implemented in the Web proxy it was quite scary how vulnerable users would be without it.

**Comment by krishnaIndia** [comment]
@theWebalyst, none of the modern browsers inject the CSP headers as of now. We don't want to enforce this on everyone. In the launcher paradigm we used to enforce it mainly because of proxy to facilitate using from all common browsers. Devs found it really difficult to get used to this paradigm of CSP. I will definitely agree that a secure site would have to define its CSP rules. 

Since we don`t have a server to enforce these headers, if an web application wants to set its own rules for CSP they can still define the rules in the [meta tag](https://developers.google.com/web/fundamentals/security/csp/#the_meta_tag) of the page.

**Comment by theWebalyst** [comment]
Sorry @krishnaIndia my mistake - I think I may be confusing CORS defaults (e.g. same origin policy) with CSP, but I can't find the nice table of what is enforced / defaulted in the different browsers and what is planned. If you have more on that please let me know so I can make a note of it.

I did find this useful guide for applying CSP in web apps tho so I'll link it here:

https://www.owasp.org/index.php/Content_Security_Policy_Cheat_Sheet

**Comment by joshuef** [comment]
@theWebalyst just to follow up here.

Web apps can set CORS with their requests, there's nothing specific in SAFE Browser blocking this over electron (for `safe:`).* And as `safe:` is a registered protocol, it should (afaik) behave in the same manner as `http`. Does that answer your question?

* We do have a [single _hack_ that removes `Origin` from requests on localhost](https://github.com/maidsafe/safe_browser/blob/master/app/background-process/ui/windows.js#L109-L120) _at the moment_. This is to prevent the protocol crashing and is related to an [electron bug](https://github.com/electron/electron/issues/10314).
