### ISSUE TITLE
Create NRS UI

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_browser#942]
Starting just with address bar tweaks: 
https://www.figma.com/file/AnUCPghMPOcBIh5Ep1FosB/Perpetual-Web-Browser?node-id=446%3A726

nice to have is full ui:
https://www.figma.com/file/AnUCPghMPOcBIh5Ep1FosB/Perpetual-Web-Browser?node-id=728%3A0

**Comment by joshuef** [comment]
A note to QA: This is not aiming to be true to the designs. But just to get the layout and flow for the components in place.

We'll have an issue for proper styling of this against the designs in a later milestone.

**Comment by S-Coyle** [comment]
Currently experiencing a 404 when attempting to register an unclaimed URL. Will return to verify this once that issue is resolved

**Comment by S-Coyle** [comment]
Basic layout and flow is there - verified on macOS
