### ISSUE TITLE
404 error when trying to register a site in packaged browser

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe_browser#987]
Replicated on both macOS & Linux.
Steps to replicate:
1. Authenticate the browser with a running vault.
2. Enter URL of a non-existing site and hit enter - click to register the site

The registration process eventually comes back with a `404 Not Found` error.

Srini tested building himself with `yarn mock-dev` and this issue did not exist, but then after packaging it locally & trying again the issue was back.

**Comment by calumcraig** [comment]
Testing on released version 0.15.

This issue is now resolved - user is presented with the option to edit page:

![image](https://user-images.githubusercontent.com/44327924/65756437-02d74e80-e10d-11e9-980c-975aed8b350a.png)

Closing this issue and moving to done.

**Comment by calumcraig** [comment]
Above is on Linux. Confirmed correct behaviour on macOS too:

![image](https://user-images.githubusercontent.com/44327924/65757015-26e75f80-e10e-11e9-93c6-0e09c105f7cf.png)
