### ISSUE TITLE
"Click above to edit the page and make it your own" text appears on sites that you don't own

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe_browser#988]
![image](https://user-images.githubusercontent.com/37112040/65526196-9c71e680-dee8-11e9-8574-bd9bacc1f234.png)

Should this text only appear when you visit URLs that you have registered?
If the logged in user didn't register the site then, as in the screenshot above, they do not see the edit icon and so this text makes no sense to them.

**Comment by calumcraig** [comment]
The message displayed has been updated in line with the above comments:

![image](https://user-images.githubusercontent.com/44327924/65757157-7cbc0780-e10e-11e9-97b2-3c0e5cf01762.png)
