### ISSUE TITLE
Linux v0.4.0 ~/.local/share/icons must exist or fail to open

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_browser#99]
Operation System: linux-x64.zip on Linux Mint 18.1
Beaker Version: v0.4.0

Fails to open and gives a javascript error, if icon directory does not exist.
= ~/.local/share/icons

Ctrl-C to stop commandline and then restarting having created that directory, it does work.. putting the icon in that directory then.

![screenshot](https://user-images.githubusercontent.com/1708690/28980806-1a421260-7947-11e7-8846-a5789594431e.jpg)

**Comment by hunterlester** [comment]
I'm going to have to research a little to understand what's happening. 

I wonder if Electron is supposed to create that directory path and load the icon into it?

You are simple executing SAFE Browser binary, yes?

**Comment by davidpbrown** [comment]
Yes.. immediately after starting the binary.. and didn't occur with Test17.

**Comment by JPL1** [comment]
Also happens with Fedora 25

**Comment by krishnaIndia** [comment]
Should be resolved with #105
