### ISSUE TITLE
Issue with fetching `mySites` from `local/shared vaults`

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe_browser#991]
`My Sites` in the browser is listing the sites I've created in the local vault, which is now deleted.

The scenario is:
I've created few sites in the local vault, then I've replaced the local vault with the shared vault's config file. I've created the new site in the shared vault.
![Annotation 2019-09-25 132102](https://user-images.githubusercontent.com/27578024/65583115-43fc2100-df9c-11e9-8e5c-605968a706b7.png)

In the above SS, the first two sites are created using local vault, which is now deleted. the third one is created in the shared vault. Launching the browser after replacing the shared vault, still I'm able to see the list of sites from the deleted vault

So, @manavbp and I were debugging and confirming that the list is being fetched from a file called `mySites.json` in the location `~/.config/Electron` in Ubuntu, as shown below.
![Annotation 2019-09-25 132028](https://user-images.githubusercontent.com/27578024/65583528-05b33180-df9d-11e9-8c79-4e649f02a078.png)

**Comment by joshuef** [comment]
I'd opt to mark this as `wont-fix` as the local save is temporary until we have containers set up. 

If you change vaults, you will have to remove the temporary file for now. If this isn't acceptable, we can talk about what to do. But I don't think this is worth spending that much time on at the moment.
