### ISSUE TITLE
macOS - Browser intermittently crashes when opening Dev Tools

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe_browser#992]
Intermittent, but I have now come across this 3 or 4 times now on macOS, and Calum has also just come across it on macOS.
Issue seems to only occur when there is a problem, e.g. a 404 page on the browser, and so I attempt to open dev tools to see if any warnings or errors - this can result in the browser closing itself down.

**Comment by joshuef** [comment]
sounds related to #999

**Comment by S-Coyle** [comment]
@joshuef not sure if they are related - when I was replicating this bug I was attempting to open dev tools on a safe website tab using the macOS keyboard shortcut, then it was crashing the whole browser. Wasn't attempting to open on the My Sites, Bookmarks or History pages (noticed that nothing at all happens when opening on these)

**Comment by joshuef** [comment]
Okay, so happening on normal sites as well as error pages 👍

**Comment by S-Coyle** [comment]
Reported in the forum - https://forum.safedev.org/t/safe-browser-v0-15-4-2056-bug/2734?u=stephenc
Reproduction steps given:

```
Using SAFE Browser v0.15.4.2056 on macOS 10.14.5 I can reproduce a crash.
1. Load a FilesContainer xor-url via the address box.
2. Open the developer tools with option+command+i.
```

**Comment by S-Coyle** [comment]
Some information from latch in the forum thread on a potential workaround...
FWIW I’ve found a workaround that avoids the crash approx. 20% of the time.

Start SAFE Browser.
Open new tab.
Open dev tools.
Open destination address.
Adding the second tab appears to help.

**Comment by S-Coyle** [comment]
@joshuef reproduced with safe browser alpha v0.16.0 on macOS 10.15.2.
Repro steps:
1. Launch SAFE Network App Alpha and log into shared vault.
2. Launch SAFE Browser v0.16.0-alpha.
3. Open a new tab on browser and open a safe page, I used safe://glasgow.
4. Toggle open dev tools

Dev tools flashes up for a brief moment then the browser crashes
